### ISSUE TITLE
newest code /api/login will return 403

### ISSUE THREAD

**Issue by gggin** [jedireza/aqua#100]
same problem with

https://getaqua.herokuapp.com/

**Comment by jedireza** [comment]
Thanks for opening an issue. Could you be more clear? What's the bug? How can I reproduce it?

**Comment by gggin** [comment]
go to this https://getaqua.herokuapp.com/
 then login page
then input root root
then forbidden

In my own build same problem!

**Comment by jedireza** [comment]
It's not giving me a 403 on desktop chrome but it is on Android chrome. I suspect this is from the `crumb` csrf config. If you remove the `crumb` plugin from the `manifest.js` file you should be unlocked for now.

We may need to configure csrf differently.

**Comment by gggin** [comment]
Sure, thank you for debug this problem!
