### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by 3HMonkey** [jedireza/aqua#102]
Hey and thank you for the wonderful project. BTW, is there a chance you release a migration guide for projects which are already in development?
Here are some more information: I am very new to javascript and node but I have many (10 years) experience of php. I used phpstorm/webstorm to generate the node project files.

**Comment by jedireza** [comment]
> Hey and thank you for the wonderful project.

Thank you

> BTW, is there a chance you release a migration guide for projects which are already in development?

I didn't plan on it. If you're migrating from an older version of Aqua, I suggest you compare a simple section like Statuses and note the differences. There are quite a lot of changes though.

> I am very new to javascript and node but I have many (10 years) experience of php. I used phpstorm/webstorm to generate the node project files.

Cool. In these situations I suggest giving yourself time to get comfortable with Node.
