### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by SamuelzXu** [jedireza/aqua#103]
How do I push to heroku without getting a bunch of errors in the logs and having the application crash? It cannot run the command "gulp", so after i changed the npm start script to "node server.js" it still did not work.

**Comment by jedireza** [comment]
Thanks for opening an issue.

Take a look at the wiki page. https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku

If you have more questions we can re-open this issue.
