### ISSUE TITLE
API does not work with aqua

### ISSUE THREAD

**Issue by madnight** [jedireza/aqua#107]
From the README: "If you don't use React and/or would rather bring your own front-end, checkout Frame. It's just the HTTP API parts of Aqua."

So Aqua should also work as HTTP API so i'll try:
```
POST
https://getaqua.herokuapp.com/api/login
with
{
	"username": "root",
	"password": "root"
}
and i get
{
  "statusCode": 403,
  "error": "Forbidden"
}

```
But if i try this with 
```
https://getframe.herokuapp.com/api/login
then it works as expected
{
  "user": {
    "_id": "000000000000000000000000",
    "username": "root",
    "email": "jedireza@gmail.com",
    "roles": {
      "admin": {
        "id": "111111111111111111111111",
        "name": "Root Admin"
      }
    }
  },
  "session": {
    "userId": "000000000000000000000000",
    "key": "101931c4-3a91-4edc-9844-9f9813cbc248",
    "time": "2016-09-16T09:22:17.253Z",
    "_id": "57dbb9c9eebca40003eeead2"
  },
  "authHeader": "Basic NTdkYmI5YzllZWJjYTQwMDAzZWVlYWQyOjEwMTkzMWM0LTNhOTEtNGVkYy05ODQ0LTlmOTgxM2NiYzI0OA=="
}

```

So API does not work with aqua anymore?

**Comment by jedireza** [comment]
It does. Aqua has CSRF setup though. There's a wiki page on this here:
https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints

If you find out this isn't related to `crumb`, or caused by another bug, let's re-open this issue.
