### ISSUE TITLE
I can't run aqua on windows

### ISSUE THREAD

**Issue by lealexandre** [jedireza/aqua#108]
The app seems to crash when i try to run it
![screenshot_install-aqua](https://cloud.githubusercontent.com/assets/10567114/18604176/3bc045d6-7c2e-11e6-83c5-68f6888e35f8.png)

**Comment by jedireza** [comment]
Thanks for opening an issue.

I see in the output there: `node: bad option: --inspect`.

Try removing the `--inspect` option from the `./gulp/nodemon.js` file and let us know if the app starts up.
https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/gulp/nodemon.js#L8

By the way, what version of node are you running? Let's see the output of `$ npm version`.

**Comment by lealexandre** [comment]
Thanks a lot Reza. It runs now. Node version=4.5.
Starting playing with aqua now... :)

**Comment by jedireza** [comment]
Nice. I have set the engines property in [`package.json`](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/package.json#L16-L18) to `>= 6.0.0` and I'm only testing against v6.x on Travis.

I'd like to know if you upgraded to v6.x if `--inspect` would work on Windows. It's a super simple way to get a debugger running for your app.

Also, FYI, v6.x enters LTS in a few weeks. I try to use the latest stable version.
https://github.com/nodejs/LTS#lts-schedule

**Comment by lealexandre** [comment]
Hi Reza,

I updated to v6 and it runs normally. I should notify though that during the install, I ran into a "Cannot find module 'unicode/category/So'" which was fixed by install unicode locally.

Best,

Alexandre

**Comment by jedireza** [comment]
> I updated to v6 and it runs normally.

You mean with the `--inspect` flag?

> I should notify though that during the install, I ran into a "Cannot find module 'unicode/category/So'" which was fixed by install unicode locally.

Hmm. `unicode` is not a direct dependency of ours. I think it's being brought in from `slug`, which we are using. I just did a fresh install and didn't see that message. Could be a fluke. If you see it consistently, and we have steps to reproduce, we should open an issue with `slug` and/or `unicode` as needed.

**Comment by lealexandre** [comment]
Yeap, install works with --inspect flag.

I haven't tried new installs yet.
