### ISSUE TITLE
Move shared admin components

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#109]
The [`client/components/admin/*.jsx`](https://github.com/jedireza/aqua/tree/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/components/admin) files should move to `client/pages/admin/components/`.

**Comment by GuilhermeJabur** [comment]
Hey @jedireza, let me take it. :D

**Comment by jedireza** [comment]
👍 it's all you

**Comment by GuilhermeJabur** [comment]
@jedireza , can u create a new remote branch for the issue so i can push?

Thanks

**Comment by jedireza** [comment]
You should fork this repo, create a feature branch and create your pull request against that. 

These may help:

 - https://help.github.com/articles/working-with-forks/
 - https://help.github.com/articles/creating-a-pull-request-from-a-fork/
 - https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by GuilhermeJabur** [comment]
sure, thanks!

**Comment by jedireza** [comment]
Closed via #177
