### ISSUE TITLE
Create shared components for notes and status

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#110]
The [notes](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/pages/admin/accounts/details/note-form.jsx) and [status](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/pages/admin/accounts/details/status-form.jsx) components (currently only on [admin > account > details]) should be made into shareable components.

Related to #109

**Comment by alecarg** [comment]
@jedireza , what are statuses in the context of this web app?

**Comment by jedireza** [comment]
@GuilhermeJabur would you like to work on this?

**Comment by GuilhermeJabur** [comment]
what do you mean by "made the components into shareable"?

**Comment by jedireza** [comment]
Let's imagine we wanted to apply notes or status to another record besides accounts (like admins for example). In that case, we should be able to share the notes and status components (like we do with the shared delete form).

**Comment by GuilhermeJabur** [comment]
Going to do it this weekend.

**Comment by jedireza** [comment]
I actually had these mostly done locally 😉.

**Comment by jaburcodes** [comment]
ok
