### ISSUE TITLE
Heroku Deploy Error

### ISSUE THREAD

**Issue by SamuelzXu** [jedireza/aqua#111]
When running the command "heroku run npm run first-time-setup --app myapp", it runs it, then throws the error "cannot find module promptly" and that the command "node first-time-setup.js" fails even though I have it up and running locally.

**Comment by jedireza** [comment]
Thanks for opening an issue.

[`promptly` is a dev dependency](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/package.json#L79), sounds like it didn't get installed on Heroku.

Have you set the environment variable `NPM_CONFIG_PRODUCTION=false` for your Heroku app? See: https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#dependencies-and-build-files

**Comment by jedireza** [comment]
Thanks for opening an issue.

[`promptly` is a dev dependency](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/package.json#L79), sounds like it didn't get installed on Heroku.

Have you set the environment variable `NPM_CONFIG_PRODUCTION=false` for your Heroku app? See: https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#dependencies-and-build-files

**Comment by jedireza** [comment]
Hmm. You'll need to figure out why `promptly` didn't get installed when you deployed to Heroku. I can check that promptly got installed for the live demo like this:

```bash
$ heroku run npm ls promptly --app getaqua
Running npm ls promptly on ⬢ getaqua... up, run.9956
aqua@5.0.1 /app
`-- promptly@2.1.0 
```

**Comment by SamuelzXu** [comment]
Okay, i got it working somehow.. Now, when I try to signup an account or sign in to my root account on heroic, it gives me a “Forbidden” error. Any possible reasons? Thanks for the help!

**Comment by jedireza** [comment]
https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints
