### ISSUE TITLE
FilterFormHOC should spread props to consumer

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#113]
https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/components/admin/filter-form-hoc.jsx#L61

Currently we're passing the the loading prop like this: `loading={this.props.loading}`. But we should just spread all the props like `{...this.props}` to the `FilterForm`.

Related to: #109

**Comment by GuilhermeJabur** [comment]
Could you explain it a little better?

**Comment by jedireza** [comment]
Yeah, since this HOC can be used in many places, sometimes you may want to have custom props passed to your lower order component.

If we simply `{...this.props}`, then consumers can add any props they want.

**Comment by jedireza** [comment]
@GuilhermeJabur would you like to work on this?

**Comment by GuilhermeJabur** [comment]
sure, let me take it, it's a very simple one :D
