### ISSUE TITLE
Would someone have time to help me out to start a map based app on aqua?

### ISSUE THREAD

**Issue by lealexandre** [jedireza/aqua#115]
Hi there,

I'm trying build a small map based app on top of Aqua. Would someone have time to help me out?
My skype id is lealexandre1

Best,

Alexandre

**Comment by jedireza** [comment]
What kind of help are you looking for? Are there specific questions you have?

**Comment by lealexandre** [comment]
Ideally I'm looking for some help to implement a specific feature (user's favorite locations on a map). I'm willing to compensate this person.

**Comment by jedireza** [comment]
Closing. Maybe you'll have more luck [search for freelancers](https://www.google.com/#q=node.js+freelancers) and/or similar service.
