### ISSUE TITLE
Using a different DB

### ISSUE THREAD

**Issue by Nojopar** [jedireza/aqua#116]
Is it possible to use a different DB than MondoDB?  We have existing systems which require SQL Server and we'd like to use this interface to SQL server instead.  We can create tables that match the MondoDB schema pretty easily, so that shouldn't be an impediment.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Is it possible to use a different DB than MondoDB?

Sure. You'll need to re-write [the models](https://github.com/jedireza/aqua/tree/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/server/models).

Keep me posted, I'm interested to see where you take it.

**Comment by Xeoncross** [comment]
@jedireza I am thinking about porting the models to MySQL. However, I'm unsure how to keep the option for either DB open. I was thinking about simply separating the models by folder, but there are a lot of files that assume mongo-models so this would be a big change.

**Comment by jedireza** [comment]
Porting is cool. Though I don't think it's worth the overhead to try making them compatible. Is that an issue you're facing specifically or just an idea or nice-to-have?

**Comment by Xeoncross** [comment]
Aqua would provide a nice transition layer for existing PostgreSQL/MySQL/MariaDB applications if it supported SQL. I don't really want to remove the MongoDB option though since many users would rather have it. At the moment was was just reading over the code to see if there was any sane way to handle this.

**Comment by jedireza** [comment]
I'm not convinced that's something we should have built-in to Aqua by default. My first thought is this sounds better as a fork, if that's your route I'd like to see Frame forked instead of Aqua do folks could add whatever frontend they like most.

**Comment by Xeoncross** [comment]
Makes sense, bootstrap vs material design is another equally big choice people might want but we can't have everything. Really nice repo by the way, everything from helmet to joi to react-router v4.

**Comment by jedireza** [comment]
Thanks. Do let me know if you port or fork. I'd love to see how it turns out.

**Comment by jimlowrey** [comment]
HI all, 
  I forked of Aqua to use [Sequelize](http://docs.sequelizejs.com/) and [Postgresql](https://www.postgresql.org/) at [github.com/jimlowrey/aqua-sql](https://github.com/jimlowrey/aqua-sql).  There is a live demo at [aqua-sql.herokuapp.com](https://aqua-sql.herokuapp.com/).

  I agree with @jedireza about forking.   I had to change the models as well as add new models.   There is a lot going on in the mongo documents that takes some effort to simulate in a relational way.  Additionally the API for mongo-models is considerably different than sequelize.  Those APIs would have to be abstracted out.  This is evident in the server API handlers.

  @Xeoncross please take a look.  I imagine there are a few bridges you will be running into that I've already crossed.
  @jedireza thank you for Aqua.  In vast world of options for Node, React, and Redux, Aqua provided library choices and patterns that I could latch onto and move forward with.

**Comment by Xeoncross** [comment]
@jimlowrey thank you for your work. Is there anything you would like community support with?

**Comment by jimlowrey** [comment]
@Xeoncross you are welcome.  The first thing that comes to mind is how best track this project in a Git way.  The second is general code improvements.  I'll open those issues in the project.  Thanks for taking a look.

**Comment by jedireza** [comment]
This is rad. Thanks for sharing!
