### ISSUE TITLE
Modal component should not set `top` style

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#119]
There's a bug with the modal dark transparent background not covering the page properly when we scroll a bit and then open the modal.

https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/components/modal.jsx#L85

Simple fix: Simply set `top` to `0px` instead of `document.body.scrollTop`.

**Comment by sanrock1** [comment]
Can you point out where can I see the modal? (eg. press this button on this particular page)

**Comment by jedireza** [comment]
In the admin screens (ex: Admin > Accounts) you can see a "create new" button that will open the modal.
