### ISSUE TITLE
"npm start" fails while "node server.js" works.

### ISSUE THREAD

**Issue by younesouhbi** [jedireza/aqua#120]
Hi there,
Thanks for this huge time saver component.
I'm new to node so I may be missing something obvious here. I followed the instructions on how to get started to the letter, bcrypt didn't work at first so I deleted everything and started over by doing the following:

1. Cloned the repo
2. Replaced bcrypt with bcryptjs as mentioned in the wiki (even though 2 of last test files didn't need replacements while still being mentioned as they did)
3. Did "npm install" after replacing bcrypt with bcryptjs
4. Didn't have to change any config since MongoDB is using the default port
5. Run "npm run first-time-setup". Entered what was required. It succeeded.
6. Run "npm start", it runs fine until it shows "app crashed..." then continues. Opening localhost:8000 doesn't work, like there's nothing on the end of it. It also complains that "--inspect" is a bad option.

Running "node server.js" works however just fine and I'm able to log in using the root email/password and navigate the different pages.

Any idea what could be the problem? My platform is Windows Server 2012 R2.
Thank You

**Comment by jedireza** [comment]
Thanks for opening an issue.

What version of node/npm are you using. To find out simply run `$ npm version`. The output looks like this:

```bash
$ npm version
{ aqua: '5.0.1',
  npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.6.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.83',
  zlib: '1.2.8' }
```

Also post your terminal output with the errors.

**Comment by younesouhbi** [comment]
Hi,
Thank you for your reply. I apologize for getting back to you on this so late, I was away.
Below are the details about the node version.

`{ aqua: '5.0.1',
  npm: '2.15.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.3',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }`

Is my node version outdated?
Thanks

**Comment by jedireza** [comment]
https://github.com/nodejs/LTS

Soon node@v4 is going into LTS. I'm using node@v6.

IIRC `--inspect` was added to node@v6.3.x so you can either upgrade or remove the `--inspect` option from the [`gulp/nodemon.js`](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/gulp/nodemon.js#L8) file.
