### ISSUE TITLE
Created admin account cause error

### ISSUE THREAD

**Issue by L30Yu** [jedireza/aqua#121]
Thanks a lot for this project.

npm start works fine.

I used my root account created couple Admin Group and Admin users.

Then I created an account, testadmin, and loged in.

Then I use my root account to link this testadmin with an created Admin user.

Then I use testadmin log out and log in again, it shows me Admin panel, cool.....

However, if I click Admins, Admin Group buttons, it does not really work properly, the Admin Group does not shows up any record, 
Sometimes, after i lick Admins, I got 2 accounts records, But If I click Admin Group, the page does not even change

and I got these errors:
`Debug: pre, error 

    {"msec":0.5672759991139174,"assign":"ensureAdminGroup","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Missing admin group membership to [root]."},"headers":{"content-type":"application/json; charset=utf-8","strict-transport-security":"max-age=15768000","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-download-options":"noopen","x-content-type-options":"nosniff","cache-control":"no-cache","vary":"accept-encoding","content-encoding":"gzip"}}}}

Debug: pre, error 

    {"msec":0.5735299997031689,"assign":"ensureAdminGroup","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Missing admin group membership to [root]."},"headers":{"content-type":"application/json; charset=utf-8","strict-transport-security":"max-age=15768000","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-download-options":"noopen","x-content-type-options":"nosniff","cache-control":"no-cache","vary":"accept-encoding","content-encoding":"gzip"}}}}

Debug: pre, error 

    {"msec":0.4814910013228655,"assign":"ensureAdminGroup","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Missing admin group membership to [root]."},"headers":{"content-type":"application/json; charset=utf-8","strict-transport-security":"max-age=15768000","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-download-options":"noopen","x-content-type-options":"nosniff","cache-control":"no-cache","vary":"accept-encoding","content-encoding":"gzip"}}}}`

**Comment by jedireza** [comment]
Thanks for opening an issue.

The key thing that sticks out to me is:

> Missing admin group membership to [root]

Out of the box, this is to be expected. By default we don't let administrators manage other administrators unless they're part of the `root` group. And I don't suggest adding administrators to that group either. What I do suggest is to change route authorization to fit your specific needs.

Here is an example of where we add this check to a route config: https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/server/api/admins.js#L34-L36

Here is where you can put new authorization "preware" (similar to `ensureAdminGroup`).

https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/server/auth.js#L74

Also take a look at the route config `auth` options:
http://hapijs.com/api#route-options
