### ISSUE TITLE
how we can change title in home page aqua to comevents

### ISSUE THREAD

**Issue by MuhammadTahirkhan** [jedireza/aqua#123]
![untitled](https://cloud.githubusercontent.com/assets/15019853/19426083/11205b6c-9453-11e6-9337-877c04d7e83b.png)

**Comment by jedireza** [comment]
That can be changed in this file: https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/server/web/home/index.jsx#L13

**Comment by MuhammadTahirkhan** [comment]
Thanks for help...!
