### ISSUE TITLE
how we can change admin area picture 1 to picture2

### ISSUE THREAD

**Issue by MuhammadTahirkhan** [jedireza/aqua#125]
![untitled1](https://cloud.githubusercontent.com/assets/15019853/19445983/1f40f366-94b0-11e6-9360-9df448bc8210.png)
![untitled2](https://cloud.githubusercontent.com/assets/15019853/19445987/289f99d0-94b0-11e6-92ba-0f48d44920ec.png)

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm not exactly sure what you mean, could you add more detail please?

**Comment by MuhammadTahirkhan** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/15019853/19448095/bcdf4db2-94b9-11e6-82b7-5defa372ad42.png)

**Comment by MuhammadTahirkhan** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/15019853/19448145/f626c776-94b9-11e6-8e5f-e40a9134e2f0.png)

**Comment by jedireza** [comment]
The admin home page component is here:
https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/client/pages/admin/home.jsx

**Comment by MuhammadTahirkhan** [comment]
How we can login to admin area

**Comment by MuhammadTahirkhan** [comment]
How we can login to admin area...!
