### ISSUE TITLE
Trying to understand performance

### ISSUE THREAD

**Issue by atsepkov** [jedireza/aqua#126]
Hi, I'm a big fan of your earlier project (Drywall) and have used it to bootstrap a couple of my own web apps I use personally. I've looked at Aqua a few times but have been hesitant to switch to it because of the following:

- I'm not as quick as others to jump on the React bandwagon. To me the maintenance cost of fragmenting HTML into separate files/components seems higher than ease of not having to think about how the DOM is rendered. However, with my current app, I need to generate a lot of complex and dynamic components and it's starting to look like React may be a better fit for that than Backbone + jQuery.
- Earlier version of Aqua seemed somewhat sluggish, although I'm playing with the demo now and the sluggishness seems to have disappeared. I've experienced similar sluggishness in other modern web apps and more and more started to notice by browsing their DOM that many of them share the same thing in common: they use React. At first I attributed this to the overhead penalty of React itself, but Facebook doesn't seem to share the same sluggishness and now neither does Aqua. I wanted to understand if this is simply a result of using React improperly and if the recent refactor of Aqua I see in the commits was to fix this sluggishness? Is there anything I should be aware of as I build out my app using this to prevent hindering performance?

Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Hi, I'm a big fan of your earlier project (Drywall) and have used it to bootstrap a couple of my own web apps I use personally.

Thanks, that's always nice to hear.

> I'm not as quick as others to jump on the React bandwagon. To me the maintenance cost of fragmenting HTML into separate files/components seems higher than ease of not having to think about how the DOM is rendered. However, with my current app, I need to generate a lot of complex and dynamic components and it's starting to look like React may be a better fit for that than Backbone + jQuery.

It took me a while to give it a shot too. I really like it a lot now though.

> Earlier version of Aqua seemed somewhat sluggish, although I'm playing with the demo now and the sluggishness seems to have disappeared.

Hmm, that's the first time hearing this. However, I don't think we were bundling for production as well as we are now. Checkout the history of [`./gulp/webpack.js`](https://github.com/jedireza/aqua/blame/master/gulp/webpack.js)

> I've experienced similar sluggishness in other modern web apps and more and more started to notice by browsing their DOM that many of them share the same thing in common: they use React. At first I attributed this to the overhead penalty of React itself, but Facebook doesn't seem to share the same sluggishness and now neither does Aqua. I wanted to understand if this is simply a result of using React improperly and if the recent refactor of Aqua I see in the commits was to fix this sluggishness? Is there anything I should be aware of as I build out my app using this to prevent hindering performance?

With the latest version I did search the web about packing/bundling a react app for production, influencing the changes to our webpack config. One article that did stick out was this one:

 - http://moduscreate.com/optimizing-react-es6-webpack-production-build/

**Comment by jedireza** [comment]
I just came across this and thought I'd leave a link here:

https://github.com/lcxfs1991/blog/issues/15
