### ISSUE TITLE
How we can login to Admin area...!

### ISSUE THREAD

**Issue by MuhammadTahirkhan** [jedireza/aqua#127]

**Comment by alecarg** [comment]
I believe the real question is something more like: how can we create an admin user?

**Comment by alecarg** [comment]
@MuhammadTahirkhan , you need an admin account. It's **root / root** for the Demo.

On your local, you should get a prompt when running **npm run first-time-setup** to create your admin account.

Now on Heroku, when doing **heroku run npm run first-time-setup --app myAppName**, I get a timeout and I'm unable to create an admin user. Any help with that bit?

Thanks,

**Comment by jedireza** [comment]
@MuhammadTahirkhan yes please try to elaborate on what you need help with.

@alecarg 

> Now on Heroku, when doing `heroku run npm run first-time-setup --app myAppName`, I get a timeout and I'm unable to create an admin user, but the process does seem to run because the site now works and I'm able to register as usual. Any help with that bit?

Could you share the output of that command on Heroku?

**Comment by MuhammadTahirkhan** [comment]
Thanks...!

**Comment by alecarg** [comment]
@jedireza, I believe I was getting false negatives as my port 5000 was blocked. I was able to run the command by adding :detached like so:

**heroku run:detached npm run first-time-setup --app myAppName**

Problem I have now is that I never get any prompts, and thus the script never executes completely. When checking the log for the execution, I can see it exiting after prompting to enter the mongoDbUri. Could this be related to heroku or promptly?

**Comment by jedireza** [comment]
I'm not sure I never ran into that. However I assume `:detached` is preventing the prompts from showing:

```
run:detached COMMAND   #  run a detached dyno, where output is sent to your logs
```
