### ISSUE TITLE
Escape strings fed to RegExp to prevent crashes

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#132]
Anywhere we're creating `RegExp` objects using user data we need to escape it to prevent invalid regular expressions that can throw errors.

For example searching for `*.*` create's an invalid regular expression, and throws an error, which will crash an app. _Please don't crash the demo._ 😉 

We should install [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp) and patch the following files:
- server/api/accounts.js 
- server/api/admin-groups.js 
- server/api/admins.js 
- server/api/statuses.js 
- server/api/users.js 

Example patch:

``` diff
const EscapeRegExp = require('escape-string-regexp');

// ...

if (request.query.pivot) {
-    query.pivot = new RegExp('^.*?' + request.query.pivot + '.*$', 'i');
+    query.pivot = new RegExp('^.*?' + EscapeRegExp(request.query.pivot) + '.*$', 'i');
}
```

**Comment by ivanph** [comment]
I'm looking into this and I noticed that this doesn't happen for `GET api/users` because the route validates the value for username with [`Joi.string().token()`](https://github.com/hapijs/joi/blob/master/API.md#stringtoken), is there a reason why this can't be done for the others instead of escaping?

**Comment by jedireza** [comment]
I think because `Joi.string().token()`

> Requires the string value to only contain a-z, A-Z, 0-9, and underscore _.

So you couldn't have spaces for example.

**Comment by ivanph** [comment]
Yeah, my question was more about why only that endpoint uses token() . Are the others supposed to allow any kind of string ?

**Comment by jedireza** [comment]
Ah good question, probably because the model defines usernames as `Joi.string().token()`s.

https://github.com/jedireza/aqua/blob/9b7d0c9be46c400e05c60f48eec092070b298c96/server/models/user.js#L182

But since during `POST`, usernames are limited, we could drop that for the search page.

https://github.com/jedireza/aqua/blob/9b7d0c9be46c400e05c60f48eec092070b298c96/server/api/users.js#L137
