### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by bluepeter** [jedireza/aqua#133]
Can you consider adding email confirmation flow?

Perhaps consider either:

- Send email confirmation link on account signup
- Take user to semi-logged-in state that invites them to check their email to confirm, or to resend confirm link
- Click of confirmation link completes account signup

Or:

- Send email confirmation link on account signup
- Allow full login without email confirmation
- On click of confirmation link, set a `emailConfirmed` flag on the account to true

**Comment by jedireza** [comment]
Thanks for creating an issue.

[Drywall](https://github.com/jedireza/drywall/) used to have this, as well as third party logins. I believe having these things built-in creates bloat and increases maintenance effort. I'd be more interested in taking things out rather an adding more.

Account confirmation can be done in many different ways (email, sms, etc...). In these cases, I think it would be better for us to create guides/tutorials and add them to the wiki.

If anyone is interested in helping create a guide or know of one that we could link to, please chime in on this thread.
