### ISSUE TITLE
Do you plan to release npm version of your platform?

### ISSUE THREAD

**Issue by symbianm** [jedireza/aqua#135]
I would like to use your Aqua platform as a base for my projects, because it contains functionality that requires almost any website. It would be nice to have npm version of your platform and use it as dependency. 

It will allow to:
- exclude core code from project repo
- core updates will be much easier to deliver (just change package version)
- developer can concentrate on extending/modifications

Let me know your thoughts... Thanks in advance.

**Comment by jedireza** [comment]
Thanks for opening an issue. Since Aqua is a boilerplate it won't become a proper module.

However, many things did get extracted into proper modules over time such as `mongo-models`, `hapi-mongo-modles`, `hapi-react-views`, `flux-constant` etc...
