### ISSUE TITLE
wrong usage of route prereqs

### ISSUE THREAD

**Issue by ferrao** [jedireza/aqua#140]
On the signup route you are using a route prereq to assert if the user already exists and stop signup if that is the case.

Using a route pre-req in this way can be erroneous and lead to duplicate signup issues as checking-then-creating should be done atomically.

Typical usage of prereqs is to fetch data so that handlers can simply manipulate it on its way out

**Comment by jedireza** [comment]
Thanks for creating an issue. What's your recommendation for a fix?

**Comment by ferrao** [comment]
If you were using a db with transaction support, i would wrap all the `check-then-create` logic inside a db transaction in the route handler.

But you have MongoDB, which from what i understand does not support transactions, only atomic operations on single documents. 

I am not very skilled on MongoDB, but looking at their documentation i found two relevant pieces of information:

**Collection Update**
It seems you can perform an atomic query and update to a document as long as you have unique indexes on the fields you are querying on. Example from the docs:

```js
db.people.update(
   { name: "Andy" },
   {
      name: "Andy",
      rating: 1,
      score: 1
   },
   { upsert: true }
)
```

With a unique index, if multiple applications issue the same update with `upsert: true`, exactly one `update()` would successfully insert a new document. More info here:

https://docs.mongodb.com/manual/reference/method/db.collection.update/#db.collection.update

**Two Phase Commits**
If you need transaction like semantics for performing updates across different documents, this tutorial shows the way, although i have not read it:

https://docs.mongodb.com/v3.2/tutorial/perform-two-phase-commits/

But to be fair, i have to say that most node.js web api/app projects that i look at very rarely make use of db transactions, which still makes me wonder how they do not run into trouble more often.

Or perhaps i just worry too much and should just wait until my apps get enough concurrent traffic to cause weird things before thinking about it...

**Comment by jedireza** [comment]
Thanks for sharing. 🎉
