### ISSUE TITLE
Styling Aqua

### ISSUE THREAD

**Issue by gridworkz** [jedireza/aqua#141]
Hi Reza:

What's the best way to style Aqua? I noticed a ./client/layouts/default.less file there. Do I work directly with that?

I basically have a giant style.css file ready to go and I'm wondering how to integrate it.

Cheers, Dave

**Comment by jedireza** [comment]
Here are the entry points for the less files: https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/gulp/less.js#L11-L34

Each of those are essentially the same entry points as their js equivalents. These entry points are included in the server rendered templates.

Let's take the admin section for example:

 - the admin section includes `default.min.css` and `admin.min.css` here: https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/server/web/admin/index.jsx#L10-L11

 - you'll notice it uses the plain layout, which includes the `core.min.css` here: https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/server/web/layouts/plain.jsx#L26

This is a simple way to set things up, but the idea is that you can customize as you deem appropriate. I hope that helps.

**Comment by gridworkz** [comment]
Hi Reza:

Thanks, all clear now.

Dave
