### ISSUE TITLE
Simple question about how to use Select Form

### ISSUE THREAD

**Issue by SeanKing111** [jedireza/aqua#145]
Maybe I just don't know react well enough yet, but could you show me an example of how to use the select form?  thank you!

**Comment by jedireza** [comment]
Thanks for opening an issue.

In the admin we use `SelectControl`s a lot for the result filters. Ex: https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/client/pages/admin/accounts/search/filter-form.jsx#L37-L48
