### ISSUE TITLE
apparently --inspect is not supported in node 4.5 

### ISSUE THREAD

**Issue by olivvv** [jedireza/aqua#148]
Hi
I could not start aqua, but once I removed the '--inspect' option, it worked :
in gulp/nodemon.js
`const nodeArgs = ['--inspect'];`

**Comment by jedireza** [comment]
Correct. That's why we require node 6+

https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/package.json#L17

**Comment by olivvv** [comment]
I missed that. thanks a lot.
