### ISSUE TITLE
Server routes having 'POST' methods returns 403 regardless of security 

### ISSUE THREAD

**Issue by TomerAvni** [jedireza/aqua#151]
Hi,
I am trying to create the following handler:
```javascript
server.route({
        method: 'POST',
        path: '/plaid',
        handler: function (request, reply) {
            reply({});
        }
    });
```
However every request I am posting to this resource returns 403(Forbidden).
I've tried playing with the config part with no luck.., such as:
```javascript
 plugins: {
                'hapi-auth-cookie': {
                    redirectTo: false
                }
            },
            auth: {
                mode: 'try',
                strategy: 'session'
            },
```
I can see that the apis work ok with POST/PUT/DELETE requests.
What am I missing with web pages?

THANKS!!!

**Comment by jedireza** [comment]
Thanks for opening an issue. Have you checked out the wiki page on this?

https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints

**Comment by TomerAvni** [comment]
Well, I guess I missed it, Sorry.
I have actually meant to use it with a view and not with the plain API.
Anyway, 
Thanks.
