### ISSUE TITLE
Monitoring timeCreated&timeUpdated

### ISSUE THREAD

**Issue by TomerAvni** [jedireza/aqua#154]
What should be a good approach maintaining timeCreated&timeUpdated for the framework's models. Considering two approached were you can decorate a model with "maintain date" and another would be maintaining all.
Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue. It's really up to you and what makes the most sense in your application. I personally don't try to decorate common fields like created/updated. In practice I find there can be many more timestamps to instrument (notes, status updates, etc...).
