### ISSUE TITLE
Hot reload for .jsx files

### ISSUE THREAD

**Issue by shebatech** [jedireza/aqua#156]
Hi Jed,

Not sure if anyone else is having this issue. When I make an edit to a .jsx files, the page does not hot reload automatically, even if I refresh the page changes are not there. I have to restart the server to see the changes I have made to a .jsx file.

Is there a quick way to fix this? Hot reload works on .js files.

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue.

> When I make an edit to a .jsx files, the page does not hot reload automatically

Correct. By default Aqua doesn't include a client-side hot reloader (ex: https://github.com/gaearon/react-hot-loader).

> even if I refresh the page changes are not there

That doesn't sounds right. I just started Aqua and made changes to the home page, the admin home page, the admin navbar and all reflected the changes when I refresh the page.

Do you have steps to reproduce?

**Comment by shebatech** [comment]
Thanks again for the super fast reply. You're correct, with a refresh it does show the changes, I must've been editing another file.

I am not sure how to integrate react-hot-loader, but I will give it a shot. It will definitely speed up dev time for me since I am mostly working on front-end right now.

Thanks 👍
