### ISSUE TITLE
odd parser error with local copy of Aqua

### ISSUE THREAD

**Issue by orff** [jedireza/aqua#158]
When I git cloned the repo and ran a local instance, everything works fine.  

However, if I instead grab a zip of the repo, or recursively remove the .git folders, when I run the server, I always get:

```
Debug: internal, implementation, error
    SyntaxError: /Users/hillm/NodeJS/gravr/server/web/home/index.jsx: Unexpected token (9:21)
   7 |     render() {
   8 |
>  9 |         const neck = <link rel='stylesheet' href="/public/pages/home.min.css" />;
     |                      ^
  10 |
  11 |         return (
  12 |             <Layout
at Parser.pp$5.raise (/Users/hillm/NodeJS/gravr/node_modules/babylon/lib/index.js:4333:13)
```

Any ideas why the babylon parser dies / doesnt recognize react when its not a cloned aqua folder?

**Comment by jedireza** [comment]
Thanks for opening an issue.

That's interesting. I just downloaded a zip of master:

![screenshot from 2017-01-16 19-48-41](https://cloud.githubusercontent.com/assets/979929/22007053/cd3eacea-dc24-11e6-835b-d6f6dd88c8b0.png)

After I unzipped and ran `$ npm install`. It `$ npm start`ed up without issue.

**Comment by orff** [comment]
Thanks for the quick reply, ill try that exact same reproduction step again to see if I get the same issue again.

**Comment by orff** [comment]
Maybe a better question is "whats the suggested method of starting with aqua as a baseline then editing or overriding in a new repository ?"

**Comment by jedireza** [comment]
If you don't want the commit history:

 - clone
 - delete the `.git` folder
 - `$ git init`
