### ISSUE TITLE
Login state doesn't persist at site root

### ISSUE THREAD

**Issue by mgleed** [jedireza/aqua#160]
I'm looking into starting an app with this starter, but I notice that the login state doesn't persist when attempting to return to `https://getaqua.herokuapp.com` or other pages like `/about`. Is this intended behavior? 

I do notice, however, that after logging in, returning to the landing page, and then clicking "sign in" again, I don't have to re-enter my credentials. Perhaps the logged in state is, indeed, preserved, but the "sign-in" vs. "sign-out" button behavior is only correct on the account pages.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I notice that the login state doesn't persist when attempting to return to `https://getaqua.herokuapp.com` or other pages like `/about`. Is this intended behavior?

Yes, kind-of. If you login and then navigated your browser to `/login`, you'd get redirected. You can see us checking for that here: https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/server/web/login/index.js#L25-L33

If you wanted to add a similar kind of check on other server side routes (`/about`, `/contact`, etc...) you could.

I hope that helps.
