### ISSUE TITLE
How to add another route / page

### ISSUE THREAD

**Issue by BusbyActual** [jedireza/aqua#162]
Hey there,

I'm trying to add another page and I'm getting misc errors. Ex: "This route doesn't match any handlers"  https://puu.sh/tIE9D/c26c9ac186.png. Another example is that on submitting a form on the front end the backend the endpoint gives a 404. Previously it gave a 403 auth error and I followed your wiki to solve it. Any full stack / full page life cycle tutorial for the app would be appreciated.

Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Any full stack / full page life cycle tutorial for the app would be appreciated.

It would be great if someone wants to add a wiki page on this. I think figuring it out would be part of the fun. In general though, we're not doing anything fancy or that isn't documented in the appropriate modules. Here is a brief overview.

Server:
 - We're using hapi as the web server, so follow the trails in `./server.js`, `./server/*`.
 - One thing that can be confusing is that we use the `glue` module to compose the server, see `./manifest.js`.

Client:
 - In it's default state, the front-end is essentially 5 single page apps, some with their own routes and some without.
   - You can see this in the [webpack configuration](https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/gulp/webpack.js#L40-L44).
 - We're using `react-router` on the front-end.
   - Adding a whole new entry point will require a new server side render see `./server/www/
   - But adding a page to `/login/`, `/account/` or `/admin/` should just require a new entry in the appropriate `routes.jsx` file.

I hope that helps get you going.
