### ISSUE TITLE
Custom Aqua for another project

### ISSUE THREAD

**Issue by sminodonte** [jedireza/aqua#163]
I'd like to use Aqua in my project:
It would be a classic social network with one admin and a lots of user.
The users could create a group for example (Animals, Nature,...),become Group-admin
and invite another user to post our photo inside.
The Group-admin could give some permission and roles to another users.
Example of permission: read or write,...
Example of roles: give the opportunity to become group-admin to another Group-member

Do you think it is easy to change Aqua design?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Do you think it is easy to change Aqua design?

It wouldn't be that bad. I suggest reading this:
https://github.com/jedireza/aqua/wiki/Users%2C-Roles-%26-Groups
