### ISSUE TITLE
Login and Redirect

### ISSUE THREAD

**Issue by nitingautam** [jedireza/aqua#164]
Hi I am planning to use Aqua in  micro service kind of way, where user will login in Aqua and on successful login will be redirected to my main application.

in Aqua where I can make that change? and I believe i need to post authenticated response JSON back to my app and there I have to write a receiver, right?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Hi I am planning to use Aqua in micro service kind of way, where user will login in Aqua and on successful login will be redirected to my main application.

In it's current state the `/api/*` routes will require a CSRF token, which is instrumented on the front-end.

 - We're using the `crumb` module/plugin to accomplish this. (Configured in the `./manifest.js` file.](https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/manifest.js#L42-L49)
 - Checkout the [`./client/helpers/json-fetch.js`](https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/client/helpers/json-fetch.js#L21-L23) to see how we're getting the CSRF token and passing it back with each request.
 - Also see the wiki page on ["HTTP 403 forbidden when accessing API endpoints"](https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints)

An important question to ask is how are you going to validate user sessions in your "main" app.

I hope this helps. Good luck. Please update this thread with any learning you think would be relevant for future readers.
