### ISSUE TITLE
Reason for multiple stores

### ISSUE THREAD

**Issue by henriquesa** [jedireza/aqua#165]
Thanks for the awesome project.

I'm getting started with Redux, and trying to understand aqua's structure. Why do you have multiple stores instead of a single one for each app (account, admin)?

**Comment by jedireza** [comment]
Thanks for opening an issue. And good question.

Originally I started with one store per section. However the admin has over 40 reducers and deeply nesting them didn't seem like a good design choice. Especially when I noticed that each store is pretty self-contained. For example; we don't need to access state from admin/users in admin/statues.

In another project started with Aqua, I do have some global/shared reducers and actions (responsible for admin and user creds) which I include and use as needed. This helps reduce unnecessarily duplicating code.

I hope that helps. Also, if you have an alternative design in mind please share those ideas.
