### ISSUE TITLE
Users not visible to all Admins

### ISSUE THREAD

**Issue by nitingautam** [jedireza/aqua#168]
As per my understanding Admins can view all users created in system, correct? if a user is admin he should have all privileges like root user?

Because users created by root not visible to any other admin. is that expected?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> As per my understanding Admins can view all users created in system, correct?

Not by default. [You can see here](https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/server/api/users.js#L36), that we require root user group membership to see all users. But you could easily configure that to fit your needs.

**Comment by nitingautam** [comment]
Appreciate your quick reply. Thanks
