### ISSUE TITLE
How to restrict bot registration

### ISSUE THREAD

**Issue by metalshan** [jedireza/aqua#169]
Is there any inbuilt way to stop bot registrations in this framework?
Or I should introduce something like recaptcha?

**Comment by jedireza** [comment]
Thanks for opening an issue. There is nothing built-in to handle bot registrations.

I've never used it before, but the [react-recaptcha](https://www.npmjs.com/package/react-recaptcha) module looks like a decent option.

**Comment by metalshan** [comment]
Thanks for replying @jedireza
