### ISSUE TITLE
Aqua Node Stops after around an hour

### ISSUE THREAD

**Issue by andrewwoodard** [jedireza/aqua#17]
I've set up a node test instance of aqua on a digital ocean droplet. It runs properly for around an hour and then breaks. Any ideas on why this may be happening?

**Comment by jedireza** [comment]
Thanks for opening an issue. I don't have experience with Digital Ocean myself but the live demo for Aqua on Heroku is alive and strong. Have you seen anything in your server logs that seems suspect?

**Comment by andrewwoodard** [comment]
Reza,

Could you point me in the right direction to get verbose logging with 'npm
start' I'm having trouble getting to the reason for the break in code.


On Sat, Mar 28, 2015 at 12:50 AM, Reza Akhavan <notifications@github.com>
wrote:

> Thanks for opening an issue. I don't have experience with Digital Ocean
> myself but the live demo for Aqua on Heroku is alive and strong. Have you
> seen anything in your server logs that seems suspect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jedireza/aqua/issues/17#issuecomment-87160208>.
>



-- 
*Andrew Woodard*
Spark Fire Web Design
Cell: (585) 503-1962 <%5855031962>
661 South Ave. #406
Rochester, New York 14620

[image: Twitter] <https://twitter.com/awoodards> [image: Facebook]
<https://www.facebook.com/sparkfirewebdesign> [image: Email]
<andrew@sparkfireconsulting.com> [image: LinkedIn]
<https://www.linkedin.com/profile/view?id=63086074&trk=nav_responsive_tab_profile>
 [image: Youtube] <https://www.youtube.com/channel/UCDpWLD75PnMpnKws31x_JKA>

**Comment by jedireza** [comment]
I don't think you need to instrument anything special to look at the error logs. We'd be looking for an error stack of some kind.

Possibly similar issue: https://www.digitalocean.com/community/questions/node-js-keep-stopping-no-errors-logged

I'll leave the issue open for another day or two.

**Comment by andrewwoodard** [comment]
Reza,

That seems to be working well.

I used

forever start --spinSleepTime 10000 -l forever.log -o out.log -e error.log
server.js

and all appears to be well.

Thank you,

Andrew

On Thu, Apr 2, 2015 at 2:58 AM, Reza Akhavan <notifications@github.com>
wrote:

> I don't think you need to instrument anything special to look at the error
> logs. We'd be looking for an error stack of some kind.
>
> Possibly similar issue:
> https://www.digitalocean.com/community/questions/node-js-keep-stopping-no-errors-logged
>
> I'll leave the issue open for another day or two.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jedireza/aqua/issues/17#issuecomment-88779410>.
>



-- 
*Andrew Woodard*
Spark Fire Web Design
Cell: (585) 503-1962 <%5855031962>
661 South Ave. #406
Rochester, New York 14620

[image: Twitter] <https://twitter.com/awoodards> [image: Facebook]
<https://www.facebook.com/sparkfirewebdesign> [image: Email]
<andrew@sparkfireconsulting.com> [image: LinkedIn]
<https://www.linkedin.com/profile/view?id=63086074&trk=nav_responsive_tab_profile>
 [image: Youtube] <https://www.youtube.com/channel/UCDpWLD75PnMpnKws31x_JKA>

**Comment by jedireza** [comment]
Sweet. Glad you got it working.
