### ISSUE TITLE
new api always return 404 :(

### ISSUE THREAD

**Issue by nitingautam** [jedireza/aqua#170]
I am trying to create new API client for my project defined model, api file and manifest but when ever I try to call it, it return 404. What i am missing :(

**Manifest**

> 
>  {
>             plugin: './server/api/clients',
>             options: {
>                 routes: { prefix: '/api' }
>             }
>         }

> models: {
>                         Account: './server/models/account',
>                         AdminGroup: './server/models/admin-group',
>                         Admin: './server/models/admin',
>                         AuthAttempt: './server/models/auth-attempt',
>                         Session: './server/models/session',
>                         Status: './server/models/status',
>                         User: './server/models/user',
>                         Client: './server/models/client'
>                     },

   
**clients.js**

>  server.route({
>         method: 'GET',
>         path: '/clients/{id}',
>         config: {
>             auth: {
>                 mode: 'try',
>                 strategy: 'session'
>             }
>         },
>         handler: function (request, reply) {
> 
>            Client.findById(request.params.id, (err, results) => {
> 
>                 if (err) {
>                     return reply(err);
>                 }
> 
>                 if (!results) {
>                     return reply(Boom.notFound('Document not found.'));
>                 }
> 
>                 reply(results);
>             });
>         }
>     });
>

**Comment by nitingautam** [comment]
> exports.register = function (server, options, next) {
> 
>     server.dependency(['hapi-mongo-models'], internals.applyRoutes);
> 
>     next();
> };
> 
> 
> exports.register.attributes = {
>     name: 'clients'
> };
>

**Comment by nitingautam** [comment]
Looks like now working but now always saying "You are being redirected..." trying from curl

**Comment by jedireza** [comment]
Thanks for opening an issue. I suggest reading the hapi docs on authentication.

https://hapijs.com/tutorials/auth?lang=en_US

You may be having issues because of:

```js
auth: {
    mode: 'try',
    strategy: 'session'
}
```
