### ISSUE TITLE
Email verfication

### ISSUE THREAD

**Issue by shebatech** [jedireza/aqua#172]
Hi Jed,

Is there a way to enforce email verification on Aqua new users sign ups?

Thanks,
Tarek

**Comment by jedireza** [comment]
Thanks for opening an issue. Email verification isn't built-in. You could always implement one for your app.

Drywall did this. Maybe that old code could inspire a solution that works for you:

 - https://github.com/jedireza/drywall/blob/master/views/account/verification/index.js
