### ISSUE TITLE
Production Logging Question

### ISSUE THREAD

**Issue by mstduff** [jedireza/aqua#173]
I am trying to clean up production logs and can not for the life of me figure out why my logs are filling up with 404's (like 5mb a day), my guess is i am missing a normal browser file (favicon/robots.txt/etc)

sample message in logs:

`Debug: handler, error 
    {"msec":0.05779886245727539,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{"content-type":"application/json; charset=utf-8","strict-transport-security":"max-age=15768000","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-download-options":"noopen","x-content-type-options":"nosniff","cache-control":"no-cache","vary":"accept-encoding","content-encoding":"gzip"}},"message":"Not Found"}}`

I know this is more hapi/boom but thought i would reach out here first.

is there anyway to know what file its looking for?

**Comment by jedireza** [comment]
Thanks for opening an issue. Unfortunately with what's given it's impossible to know. I wonder if this is for a favicon or something similar. Check to see if hapi let's you add the path to logs, which would be a big help. Please update this issue with your learnings. 🙏
