### ISSUE TITLE
How can i access the menu, while on mobile?

### ISSUE THREAD

**Issue by GuilhermeJabur** [jedireza/aqua#174]
I tried to access the menu, while navigating on mobile browser, there was no button or links..

https://getaqua.herokuapp.com/

**Comment by jedireza** [comment]
The front-end doesn't have open/close mechanics instrumented like the admin does. See: https://github.com/jedireza/aqua/blob/master/client/pages/admin/navbar.jsx

**Comment by GuilhermeJabur** [comment]
So the mobile user can't navigate through the page?

May we create an issue to implement it? I would be happy to contribute.

**Comment by jedireza** [comment]
> So the mobile user can't navigate through the page?

Out of the box, on the home/about/contact/login screens, no. In the admin, yes.

> May we create an issue to implement it? I would be happy to contribute.

Essentially what we need to do is create a single page app for home/about/contact/login. This also takes us down the path of creating isomorphic/universal routes.

Sure, let's create an issue for it. I'm time poor currently though, I'll do my best to contribute and/or review.
