### ISSUE TITLE
Create Form - new screen

### ISSUE THREAD

**Issue by nitingautam** [jedireza/aqua#175]
Hi,

I have added a new section to aqua called client and when I use Create New and Post. Data is successfully stored but when it redirect to details ID is always undefined hence it throw 500

http://localhost:8000/admin/clients/undefined
http://localhost:8000/api/clients/undefined

Seems to me something related to but unable to identify as React is new for me :( any hint is appreciated. How to debug what is reaching in response object?

> 
> static createNew(data) {
> 
>         ApiActions.post(
>             '/api/clients',
>             data,
>             Store,
>             Constants.CREATE_NEW,
>             Constants.CREATE_NEW_RESPONSE,
>             (err, response) => {
> 
>                 if (!err) {
>                     this.hideCreateNew();
> 
>                     const path = `/admin/clients/${response._id}`;
> 
>                     ReactRouter.browserHistory.push(path);
> 
>                     window.scrollTo(0, 0);
>                 }
>             }
>         );
>     }

**Comment by jedireza** [comment]
Thanks for opening an issue. `response._id` is undefined and you probably need to send that `_id` back in the response. For example [in statuses](https://github.com/jedireza/aqua/blob/8726614361bf53f9fa296700af8b81f637245482/server/api/statuses.js#L120) (and most others) when we `POST` we send back the whole document which contains the `_id` field.

**Comment by nitingautam** [comment]
thanks, i used response[0]._id it worked fine.
