### ISSUE TITLE
Generating errors on npm test after 99,44% of the test covered

### ISSUE THREAD

**Issue by GuilhermeJabur** [jedireza/aqua#178]
![aqualinterror1](https://cloud.githubusercontent.com/assets/13947203/24527992/f1e94886-157a-11e7-82c4-1a35ec96a6df.png)
![aqualinterror2](https://cloud.githubusercontent.com/assets/13947203/24527991/f1e812b8-157a-11e7-80ac-48678229cc8a.png)

**Comment by jedireza** [comment]
Those are lint failures failures. The code coverage is a [known bug](https://github.com/jedireza/aqua/issues/95).

**Comment by jedireza** [comment]
FYI: These lint failures have been fixed and are on master.
