### ISSUE TITLE
Upgrade react-router

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#180]
React router v4 is current (as of 3/30/17). Let's get it upgraded.

**Comment by GuilhermeJabur** [comment]
hey jedireza, i'm on it.

**Comment by jedireza** [comment]
I started working on this earlier today. It looks like v4 was released 3 weeks ago. Is there any other indication that this is a pre-release?

**Comment by GuilhermeJabur** [comment]
sorry, u're totally right.

I thought it was pre-released because v4 was released 23 days ago and a v3.0.3 was released 6 days ago, doest it even make sense?
