### ISSUE TITLE
How to add new user role.

### ISSUE THREAD

**Issue by colin-han** [jedireza/aqua#191]
Hi, jedireza,

Just like your wiki page 'https://github.com/jedireza/aqua/wiki/Users,-Roles-&-Groups' said, 'Admin' and 'Account' are just like a user role. And we can have more than two role in system. I'm not sure my understand is correct. Does that you mean the system has ability to easily create new role? with little code？

I have take a look in source code, I found that Admin, Account and User are store in different tables, and there have server different apis and pages to support them. That means, I need create a serials of pages and apis if I want support more than two roles? Am I correct?

Thanks for your time.

**Comment by jedireza** [comment]
> That means, I need create a serials of pages and apis if I want support more than two roles? Am I correct?

Yes

**Comment by colin-han** [comment]
I see. Thank you.
