### ISSUE TITLE
Common chunk core.min.js map file not found

### ISSUE THREAD

**Issue by henriquesa** [jedireza/aqua#192]
On a fresh install, right after the postinstall build, core.min.js points its source map file to `sourceMappingURL=aqua/core.map.js`, when it's generated at `pages/core.map.js`. This is because of the webpack output option `sourceMapFilename: '[name].map.js'`, where `name` is not the full filename.

There are two quick solutions, changing `sourceMapFilename: '[name].map.js'` to `sourceMapFilename: '[file].map.js'`, or removing the line entirely, which I believe is the most appropriate option, because the default is `[file].map` and map files should be `.map`.

I'm able to open a PR for either option.

**Comment by jedireza** [comment]
Thanks for reporting and for the future PR. Choose the solution you think is best.
