### ISSUE TITLE
403:Forbidden on all API calls

### ISSUE THREAD

**Issue by FaeezBorman** [jedireza/aqua#199]
Hi There

Sorry if this is a noob issue
I start with a new project following the steps provided in the readme,
run first-time-setup, confirm the db gets created and user does exist 
after running npm start, I can see the page loads fine when i go to localhost:8000

however when I try logging in with the email and password from first setup
I get a 403 response, saying "Forbidden". I tried the same with /contact and pretty much all the api endpoints have the same problem

tried with postman as-well getting the same response

there aren't any errors in the logs

**Comment by jedireza** [comment]
https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints

Have you checked out this wiki page?

**Comment by FaeezBorman** [comment]
I haven't, will do so

Thank you so much for the quick response
