### ISSUE TITLE
Question: Suggestion for an integration with Oauth (2) 

### ISSUE THREAD

**Issue by orff** [jedireza/aqua#201]
For sharing of session on other sites.  Im hoping for someone with experience with Aqua or its dependancies who might be able to suggest to me a high level architecture or hints before I start this.

Ideally, I would be able to allow users to Authenticate using OAuth on 3rd party sites, but my aqua based API will allow them to securely allow their data to be shared on that site.

**Comment by jedireza** [comment]
For authentication take a look at Bell.

https://github.com/hapijs/bell

**Comment by orff** [comment]
Thanks, looks great!

**Comment by jloriente** [comment]
Anybody has tried the integration of bell with aqua? I think will be quite useful to support also OAuth in aqua using Bell

**Comment by jedireza** [comment]
The `bell` docs should have all the code examples necessary. Server side Aqua is just a vanilla hapi server.

I've decided against having 3rd party auth being built-in by default. It's a reasonably easy upgrade for anyone creating their own project.
