### ISSUE TITLE
Routing change causes browser refresh

### ISSUE THREAD

**Issue by Cornstar23** [jedireza/aqua#202]
Shouldn't navigating to different pages avoid a browser refresh? For instance from https://getaqua.herokuapp.com/about if you click the Contacts button you get directed to https://getaqua.herokuapp.com/contact but the browser refreshes.

**Comment by jedireza** [comment]
Yeah the whole system isn't a single page app. This may change in the future.

https://github.com/jedireza/aqua/wiki/Page-Structure-%26-How-to-add-new-page#client
