### ISSUE TITLE
config question...

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#205]
Newbie to glue and manifest.js , but can someone tell me what these 2 sections mean.. plot device, connections etc

```
    $meta: 'This file defines the plot device.',
    server: {
        debug: {
            request: ['error']
        },
        connections: {
            routes: {
                security: true
            }
        }
    },
    connections: [{
        port: Config.get('/port/web'),
        labels: ['web'],
        state: {
            isHttpOnly: false,
            isSecure: {
                $filter: 'env',
                production: true,
                $default: false
            }
        }
    }],
```

**Comment by jedireza** [comment]
`$meta` fields are treated like comments and have no side effects.

> `connections` - an array of connection options objects that are mapped to calls of `server.connection([options])`

Definitely checkout the API docs on glue here: https://github.com/hapijs/glue/blob/master/API.md

I'm not sure why I can't find the docs for `$meta` though... maybe open an issue on that repo.

**Comment by jedireza** [comment]
Ah I found it. I forgot about the `confidence` module. That's where things like `$meta` come from.

https://github.com/hapijs/confidence
