### ISSUE TITLE
Adding status when signing up

### ISSUE THREAD

**Issue by 0fork** [jedireza/aqua#208]
What would be the best way to add a predetermined status when the user signs up?

I'm not super familiar with HAPI but eager to learn so all help is appreciated.

**Comment by jedireza** [comment]
> a predetermined status when the user signs up

I'm not sure what you mean exactly.

**Comment by 0fork** [comment]
The scenario is that I would like to assign each new user to account-trial status automatically. Now I have to manually change the status in the admin panel.

**Comment by jedireza** [comment]
Oh for sure. You can customize the account creation during signup here: https://github.com/jedireza/aqua/blob/dc3e3c4d86c2c7e9a0bc934a905e8aa1a8e62968/server/api/signup.js#L96-L100
