### ISSUE TITLE
CRUD extension

### ISSUE THREAD

**Issue by bennyn** [jedireza/aqua#211]
I really like **aqua** and it's modular approach. It's great that you make use of [confidence](https://github.com/hapijs/confidence), [dotenv](https://github.com/motdotla/dotenv) and [hapi](https://hapijs.com/). The aqua project is a perfect example for the Separation of concerns design principle!

Do you plan to build another layer on top which allows easily to boostrap CRUD applications? Because this might be the next thing which people want to do after setting up a system which provides user authentication and since you already provide a connection to a database it would be just breat if you would provide an easy way to write (and maintain) custom data sets.

**Comment by jedireza** [comment]
Thanks @bennyn 🖖

> Do you plan to build another layer on top which allows easily to boostrap CRUD applications? Because this might be the next thing which people want to do after setting up a system which provides user authentication and since you already provide a connection to a database it would be just breat if you would provide an easy way to write (and maintain) custom data sets.

In what way exactly? Is there something similar you've seen that you could link to? I ask because most of the admin screens are essentially CRUD.

**Comment by bennyn** [comment]
@jedireza What I was thinking of is a scaffolding system (working like the one from Ruby on Rails, [Getting Up and Running Quickly with Scaffolding](http://guides.rubyonrails.org/v3.2.9/getting_started.html#getting-up-and-running-quickly-with-scaffolding)), which helps the developer to bootstrap a new database model including it's controller and basic view.

I know that [**Sequelize**](http://www.sequelizejs.com/) supports commands like this (to create a database model):

```bash
sequelize model:create --name TodoItem --attributes content:string,complete:boolean
```

It would be great if you could do something similar with `aqua`, so that it creates a new model and links it in the code where it should be linked to provide basic CRUD operations for the newly created entity.

**Comment by jedireza** [comment]
Ah I see. I agree, that would be great.

It does take the project down a road that's closer to being a framework and I've generally avoided that. I'd be happy if someone wanted to contribute this and we could feel comfortable with the maintenance burden it could add.
