### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#217]
hi again, 
is there an easy way I can tell aqua to generate a coverage report file?

Currently I am trying to rip out mongo and a bunch of components I don't need, but although there are no failing tests now I get a whole load of stuff like this:

478 tests complete
Test duration: 4207 ms
No global variable leaks detected
Coverage: 99.76% (27/11132)
client/actions/api.js missing coverage from file(s):
	null on line(s):
client/components/alert.jsx missing coverage from file(s):
	null on line(s):
client/components/form/button.jsx missing coverage from file(s):
	null on line(s):
client/components/form/control-group.jsx missing coverage from file(s):
	null on line(s):
client/components/form/select-control.jsx missing coverage from file(s):

etc
etc
etc for ages

**Comment by jedireza** [comment]
We're using [`hapijs/lab`](https://github.com/hapijs/lab) for testing, and there are `--coverage` and `--reporter` options.

Without being able to debug your app in it's current state, it's really hard for anyone to help further. Also realize that #95 could be a contributing factor in incorrect coverage.
