### ISSUE TITLE
access to admin panel and admin-groups

### ISSUE THREAD

**Issue by DjawadT** [jedireza/aqua#219]
hello
how i access to admin panel and admin groups?
there is 'users' collection in my database that have a user with 'root' username but password has been incrypted.

**Comment by jedireza** [comment]
After the installation, configuration and first time setup, you can run the app (via the README). Once the app is running and you have it loaded in your browser, you'll see a "sign in" link in the top right. When you're there, use the username `root` and the password you set during the first time setup procedure.
