### ISSUE TITLE
Preventing abusive signups

### ISSUE THREAD

**Issue by shatgupt** [jedireza/aqua#22]
I see there is a feature to prevent abusive logins but nothing to prevent abusive number of signups. There is email verification but shouldn't there be a captcha at signup page?

**Comment by jedireza** [comment]
Thanks for opening an issue. :sunglasses: 

Althogh we do validate that emails look like valid email addresses, we're not verifying deliverability. We left those design choices up to the developer. If someone wanted to prevent abusive signups they could use a lot of logic/code found in the abusive login detection.

Now if you leveraged a service like like [recaptcha](https://www.google.com/recaptcha/intro/index.html), you may not need to manage that extra server side logic.

I'd like to see these types of features become articles/guides that go into the [wiki](https://github.com/jedireza/aqua/wiki). [Drywall actually has an article on this.](https://github.com/jedireza/drywall/wiki/Using-reCAPTCHA) If you're willing to write one I'd be happy to collaborate and get it up on the wiki.
