### ISSUE TITLE
How do you add more "contact info" fields?

### ISSUE THREAD

**Issue by HE-is** [jedireza/aqua#220]
Sorry in advance as I'm new to node.js. Thanks for this awesome template!

I'm wanting to add more account info fields but I'm unsure which frontend files to modify.
Though I tried anyway but when I tried modifying some, to add a "fourth name" field in the name object in the accounts collection, I ended up breaking the settings page and it always ended up throwing undefined errors like "*.name.fourth is not defined"

Is there a guide/tutorial I should go through in order to understand how to add extra infor fields for the user? Or could someone give me an outline on which frontend/which files I need to change and what additions to make?

Thanks so much agian for this amazing template. I hope to wrap my head around the fundamentals to be able to use it in my project!

**Comment by jedireza** [comment]
Don't be sorry. Thanks for opening an issue. 😄 

> errors like "*.name.fourth is not defined"

This sounds like it's happening on the client side? If so, that's probably an older record not getting a default value. You can usually address this in the redux reducers.

We really should make a guide for these kinds of things. If you document the process on your journey feel free to make a wiki page. 👍

**Comment by HE-is** [comment]
Thanks! I was thinking it had something to do with states/redux. I'll try figuring it out, as well as documenting the process when I do.
