### ISSUE TITLE
code coverage html report

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#221]
modified package.json like this:

```
"test": "lab -t 99 -S -T ./test/lab/transform -L --lint-options '{\"extensions\":[\".js\",\".jsx\"]}' ./test/lab/client-before.js ./test/client/ ./test/lab/client-after.js ./test/server/ ./test/lab/server-after.js ./test/misc/ -r html -o coverage.html ",
```

but it blows up

Users/emmett/Downloads/aqua_v2/node_modules/lab/lib/reporters/html.js:210
                    const target = descriptors[originalFilename].source[originalLine];
                                                                ^
TypeError: Cannot read property 'source' of undefined
    at Object.keys.forEach (/Users/emmett/Downloads/aqua_v2/node_modules/lab/lib/reporters/html.js:210:65)
    at Array.forEach (native)
    at context.coverage.cov.files.Hoek.flatten.context.coverage.cov.files.map (/Users/emmett/Downloads/aqua_v2/node_modules/lab/lib/reporters/html.js:171:34)
    at Array.map (native)

any idea how I can generate a nice html report ?

**Comment by jedireza** [comment]
This is definitely in the `hapijs/lab` territory, so be sure to checkout those docs.

This is the last time we had a `$ npm run test-cover` script: https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/package.json#L12

I hope that helps.

**Comment by walshe** [comment]
no joy
