### ISSUE TITLE
Issues with gulp on google app engine flex

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#222]
any idea whats going on here ?  I hate app engine :(

Installed Node.js v8.2.1
 ---> c0f07624c820
Removing intermediate container 52a48535dd73
Step 3/5 : COPY . /app/
 ---> cd6ad732d7bf
Removing intermediate container 733cd07bc341
Step 4/5 : RUN npm install --unsafe-perm ||   ((if [ -f npm-debug.log ]; then       cat npm-debug.log;     fi) && false)
 ---> Running in 4de48d73d4c7

> bcrypt@1.0.2 install /app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
[bcrypt] Success: "/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> uglifyjs-webpack-plugin@0.4.6 postinstall /app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> aqua@6.5.0 postinstall /app
> gulp build

sh: 1: gulp: not found
npm ERR! file sh

**Comment by walshe** [comment]
actually I think its because gulp and a bunch of other dependencies are needed when env is production..

**Comment by jedireza** [comment]
Did you checkout the "running in production" section of the readme?

https://github.com/jedireza/aqua#running-in-production

**Comment by jedireza** [comment]
Also checkout the "dependencies and build files" section of the deploying to heroku wiki page:

https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#dependencies-and-build-files
