### ISSUE TITLE
Question about aqua vs. frame code

### ISSUE THREAD

**Issue by hortonelectric** [jedireza/aqua#226]
How do you keep the frame code up to date with aqua, manually? 

Is there a way that we could have frame as a hapi *plugin* and how hard would that be?

What advice do you have for someone who wants to keep up to date with your frame code while adding his own changes? Shall I use your origin and rebase over your code as updates come in?

**Comment by jedireza** [comment]
> How do you keep the frame code up to date with aqua, manually?

Yep.

> Is there a way that we could have frame as a hapi plugin and how hard would that be?

In it's current form, the code is meant to be a starting point for a project. Once you start customizing, it's all in your hands. We could take the ideas in these projects further and try to abstract things and make generic modules out of them, but that also comes with (even) more assumptions and maintenance burden, which I'm (currently) convinced is not worth it.

> What advice do you have for someone who wants to keep up to date with your frame code while adding his own changes? Shall I use your origin and rebase over your code as updates come in?

In my opinion, the server side code (API) is the easiest to patch manually as there are much fewer changes in that part of the code base. The hardest thing to keep updated is the client-side code.

- - - -

In the bigger picture, Aqua and Frame are really not that important, what you build with them is.

The larger your project gets, the more of a burden it will be to keep updated. Over time tools become legacy and versions drift from the most recent. If it makes sense for your project, do it.

I hope that helps. 👍
