### ISSUE TITLE
favicon & mobile nav

### ISSUE THREAD

**Issue by Kylescottw** [jedireza/aqua#228]
Hello,
Aqua is a great product, and I have two questions.
Every time I restart the server the favicon gets replaced with the aqua one. Also, how can I set a responsive nav for mobile phones on the home screen?
Thank you,
Kyle.

**Comment by jedireza** [comment]
> Every time I restart the server the favicon gets replaced

I'm not sure how you're editing the favicon but in the latest version, the favicon can be updated in the server side page templates:

 - https://github.com/jedireza/aqua/blob/4e7cb75253a04e870b73e61a73842f896ecf983e/server/web/admin/index.jsx#L15
 - https://github.com/jedireza/aqua/blob/4e7cb75253a04e870b73e61a73842f896ecf983e/server/web/account/index.jsx#L15
 - https://github.com/jedireza/aqua/blob/4e7cb75253a04e870b73e61a73842f896ecf983e/server/web/main/index.jsx#L24

> Also, how can I set a responsive nav for mobile phones on the home screen?

I just merged a new universal front-end (like 30 mins ago). This works just like the admin now. So all should be good.

**Comment by Kylescottw** [comment]
Reza,
Thank you!
