### ISSUE TITLE
webpack/node_modules ? library missing

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#231]
Hi again,

I am trying to use 'https://github.com/anthonyjgrove/react-google-login' in the app..

when I include it in package.json and install it etc and then attempt to use it in a page as described, the button is disabled..so I delved into it more..

when I use the browser debugger to view the scripts, I see no react-google-login inside the webpack/./node-modules directory ... was just wondering what the reason would be for this, is it somehow incompatible etc

thanks

**Comment by jedireza** [comment]
Using `react-google-login` is out of the scope of this project. Though if you $ npm install react-google-login --save[-dev]` then you'd need to include this in the code paths somewhere for it to be part of the dependency tree that webpack bundles up.

Though, since we're using hapijs It's probably best to work with something like [`hapijs/bell`](https://github.com/hapijs/bell) for 3rd party login/authentication.

**Comment by walshe** [comment]
thanks, I realize its out of scope..sorry for that.. I did install it and imported it, unfortunately I have to use it

```
'use strict';
const Layout = require('../layouts/default.jsx');
const Package = require('../../../package.json');
const React = require('react');

import GoogleLogin from 'react-google-login';

```

but still doesn't seem to be in the webpack/./node_modules dir, just wondering off theres some blatant incompatibility I am not seeing..

**Comment by jedireza** [comment]
If you're not getting compile errors from webpack, it's gotta be somewhere. Is it not rendering? Are you seeing any error of any kind?

**Comment by walshe** [comment]
the sign in button renders but its disabled, Ive tried it in another react-node app but don't have the issue - its really odd

**Comment by jedireza** [comment]
If it's rendering, the code is included. Why it's disabled is the real question you're faced with. 😄 Happy hunting.

**Comment by walshe** [comment]
btw , I since found out I was stupidly adding the tag to a server/web component instead of client/pages   :)
