### ISSUE TITLE
How to use modal.jsx

### ISSUE THREAD

**Issue by kylehq1** [jedireza/aqua#233]
Hello,
I see we have the modal.jsx in our components,
how do i wire it up inside the home/index.js so when i click a button the modal pops up?

Thank you.

**Comment by jedireza** [comment]
Take a look at the admin search pages, specifically the `create-new-form.jsx` components.

https://github.com/jedireza/aqua/tree/master/client/pages/admin/accounts/search

**Comment by kylehq1** [comment]
Reza,
Thank you!

How can I send you money for a coffee?
