### ISSUE TITLE
Specifying custom mongodb URL in first-time-setup not working

### ISSUE THREAD

**Issue by andyfry01** [jedireza/aqua#236]
When running first-time-setup per the instructions in the readme, the script creates a database at both the default url (mongodb://localhost:27017/aqua) and the custom one (mongodb://localhost:27017/XXXXX). This makes it impossible to log in as the admin user created by the first-time-setup script. Haven't looked into it too closely, but it seems like it is creating an admin user in one database but trying to read the info from another when the admin user attempts to sign in.

This is not a problem for users who subsequently sign up, just the admin user from the first-time-setup script. 

I think the issue stems from [line 45 in config.js](https://github.com/jedireza/aqua/blob/master/config.js#L45). For now if you're having this issue, replace `$default: 'mongodb://localhost:27017/aqua'` with the mongodb URL you'd like to use, run first-time-setup (specifying that same mongodb URL again when prompted) and it should work.

**Comment by jedireza** [comment]
Thanks for creating this issue. This is a bug.

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
