### ISSUE TITLE
Best way to pass something from Config.js into the client ?

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#240]
whats the best practice ?

**Comment by jedireza** [comment]
Good question. There really isn't a "best practice". What kinds configuration are you thinking (Ex: An S3 bucket name)? How often does it need to be updated (only once per app render)?

**Comment by walshe** [comment]
Its just a google clientid it would not change...

**Comment by jedireza** [comment]
There's an `app-state` placeholder that can be used to send the redux store state to the client. _Note: This is just a placeholder and isn't used for anything yet._

https://github.com/jedireza/aqua/blob/4e7cb75253a04e870b73e61a73842f896ecf983e/server/web/main/index.jsx#L33-L37

You could extend this idea to support a `config` prop and render a script tag with the id `app-config`:

```js
<script id="app-config"
    dangerouslySetInnerHTML={{
        __html: this.props.config
    }}
/>
```

Then on the server, in your handler you'd do something like this:

```js
const clientConfig = {
    s3BasePath: 'https://s3.amazonaws.com/mybucketname',
    googleClientId: 'some-client-id-thing'
};

// ...

request.app.config = 'window[\'appConfig\'] = ' + JSON.stringify(clientConfig) + ';'
```

Then on the client you'd assume that `window.appConfig` was an object and access your info directly; `window.appConfig.googleClientId`.

**Comment by walshe** [comment]
hmm, had been trying something like this, but not working out so good:


```
class HomePage extends React.Component {
    render() {

        const neck = [
            <link key="layout" rel="stylesheet" href="/public/layouts/default.min.css" />,
            <link key="page" rel="stylesheet" href="/public/pages/home.min.css" />
        ];
        const feet = <script src="/public/pages/home.min.js"></script>;
        
        const googleClientId = Config.get('/google/clientId');
        const hostedDomain = Config.get('/google/hostedDomain');
        
        return (
            <Layout
                title="Home"
                neck={neck}
                feet={feet} activeTab="home" googleClientId={googleClientId} hostedDomain={hostedDomain}>
                <div id="app-mount"></div>
            </Layout>
        );
    }
}

```

class PlainLayout extends React.Component {
    render() {

        return (
            <html>
                <head>
                    <title>{this.props.title}</title>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <link rel="stylesheet" href="/public/core.min.css" />
                    <link rel="shortcut icon" href="/public/media/favicon.ico" />
                    <script type="text/javascript">
                        window.googleClientId='{this.props.googleClientId}'; 
                        window.hostedDomain='{this.props.hostedDomain}';
                    </script>
                    {this.props.neck}
                </head>
                <body>
                    
                    {this.props.children}
                    <script src="/public/core.min.js"></script>
                    {this.props.feet}
                </body>
            </html>
        );
    }
}
```

**Comment by jedireza** [comment]
I don't think you can set the inside of a script tag this way without using `dangerouslySetInnerHTML`. You can see the in the output that some characters are escaped.

 - https://stackoverflow.com/questions/31276926/how-to-add-script-tag-using-reactjs

**Comment by walshe** [comment]
your solution worked nicely thanks 💯

**Comment by jedireza** [comment]
I noticed you're using the older `Layout` component. Please note that last week I shipped a new universal front-end and no longer use that pattern.

**Comment by walshe** [comment]
whats the advantage of this new way and why called 'universal' ?

**Comment by walshe** [comment]
confused, app is still not isomorphic I thought ?

**Comment by jedireza** [comment]
Universal and isomorphic are used interchangeably. The `main` front-end app is universal now. The admin and account areas are not.
