### ISSUE TITLE
Using Modal component from a main page results in "window is not defined" error

### ISSUE THREAD

**Issue by Cornstar23** [jedireza/aqua#241]
When trying to create an instance of Modal from, say, the client/main/navbar the server throws a "window is not defined" error.  Is there something I might be doing wrong or is this a bug?

**Comment by jedireza** [comment]
Please include stack traces when sharing errors. `window is not defined` isn't that helpful on it's own.

I do know that the constructor of the `Modal` component expects the global `window` to be present, which it isn't on the server.

https://github.com/jedireza/aqua/blob/4e7cb75253a04e870b73e61a73842f896ecf983e/client/components/modal.jsx#L24

The main app is universal (aka isomorphic) and get's rendered on the server. You'd need to modify the `Modal` component to detect if `global.window` exists before using it.

**Comment by Cornstar23** [comment]
Thanks. Not sure if the proper way, but I just moved 
```
this.state = {
   bgHeight: window.innerHeight
};
```
to the  componentDidMount() and set the bgHeight to 0 in the constructor instead of to window.innerHeight.

**Comment by jedireza** [comment]
If it works for you, that's all that matters. 😁
