### ISSUE TITLE
How to handle browser refresh of a React Route

### ISSUE THREAD

**Issue by walshe** [jedireza/aqua#242]
So I have greatly simplified the app which just has one app at / , and in here there is one react route called /vehicles (which becomes enabled in the menu after auithentication)

Now I have a question... I realize this is not an isomorphic application, but what is the best way to handle a browser refresh or browser url that is ../vehicles?

Obviously there is no server route at this url so I get a '{"statusCode":404,"error":"Not Found","message":"Not Found"}' . .. and all state is lost even if there was a route there

**Comment by jedireza** [comment]
This sounds outside of the scope of Aqua.

https://www.google.com/search?q=handle+browser+refresh+of+a+React+Router
