### ISSUE TITLE
Add new page wiki needs updating

### ISSUE THREAD

**Issue by andyfry01** [jedireza/aqua#244]
Hi @jedireza, been working with Aqua for a few days now, enjoying it!

One area for improvement I can see is an updated ["Add new pages" wiki](https://github.com/jedireza/aqua/wiki/Page-Structure-%26-How-to-add-new-page). The current guide is a little out of date and references code that has either changed or has been deleted. Can I make a contribution by updating the guide to make it easier for a new user to navigate?

**Comment by jedireza** [comment]
That would be great. Thanks!

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
