### ISSUE TITLE
Update PropType of value field for shared form components

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#251]
We should update the `PropTypes` for the shared form components so the values are happy to take `Number`s and `String`s.

```js
const propTypes = {
    // ...
    value: PropTypes.oneOfType([
        PropTypes.string,
        PropTypes.number
    ])
};
```

https://github.com/jedireza/aqua/tree/master/client/components/form

**Comment by jaburcodes** [comment]
hey @jedireza let me take this ;)

**Comment by jaburcodes** [comment]
is there anything missing?

**Comment by jedireza** [comment]
Nope. I just forgot to close this.
