### ISSUE TITLE
I get "Forbidden" when trying to login/signup.

### ISSUE THREAD

**Issue by HE-is** [jedireza/aqua#254]
No error pops up in the npm commandline or inspector. I don't know what's wrong. 
![2017-09-11-131839_499x360_scrot](https://user-images.githubusercontent.com/19391695/30290204-2693d222-96f4-11e7-9b64-22906a6a4774.png)

Source works on my local machine; this only happens on the ubuntu 16.04 server. 
What could be the cause? Sorry for little information... I just don't know what to do. It has to be something related to permissions, maybe with mongodb?

**Comment by jedireza** [comment]
I usually see this when I accidentally access the site without `https://`.

**Comment by HE-is** [comment]
Sorry to necro... I was just wondering if there was a way to run without ssl? It was running without before, but somehow now it requires ssl =/

**Comment by jedireza** [comment]
You need to see what the server logs say. It may also be caused by an invalid CSRF token.

**Comment by HE-is** [comment]
I'm sorry; which logs to I look in?

**Comment by jedireza** [comment]
The server logs. You need to debug hapi and see why it's returning this in your case.

**Comment by HE-is** [comment]
Okay I'm making a whole new VPS to host aqua on. I know this is very nooby, and I apologize again for the bother I am...
What is the install process if the arch linux server/vps only will be used for aqua?
Install openssh, mongodb, node, configure iptables, etc.?

**Comment by HE-is** [comment]
I just want to make sure I'm on the right track. Thanks ^_^

**Comment by jedireza** [comment]
I'm not really sure about that.
