### ISSUE TITLE
cheap-module-source-map for production ?

### ISSUE THREAD

**Issue by adantoscano** [jedireza/aqua#255]
Hi,
I found in webpack that it declares mapping with "source-map" option in dev mode and cheap-module-source-map for production. Shoudn't be the opposite?

```javascript
    let devtool = 'source-map';

    if (process.env.NODE_ENV === 'production') {
        plugins.push(new Webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }));

        devtool = 'cheap-module-source-map';
    }
```

**Comment by jedireza** [comment]
I don't think so. I forget why `cheap-module-source-map` was chosen for production. Do you think it should be different in production?

**Comment by adantoscano** [comment]
You can see here [https://webpack.js.org/configuration/devtool/](url) the tab that cheap is for a fast rebuild but not for production and the oposite with source-map.

![image](https://user-images.githubusercontent.com/10076771/30652770-842f3aca-9e29-11e7-8d66-e2ecabd9a40b.png)

**Comment by jedireza** [comment]
Want to open a PR with the fix you're suggesting?

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
