### ISSUE TITLE
Documentation on user account linking?

### ISSUE THREAD

**Issue by rocky1138** [jedireza/aqua#256]
Just trying to wrap my head around the user permissions system. It all makes sense except for this notion of linking users. Can you describe that a bit? When would we need that, why we'd use it, when we wouldn't want it, etc.?

**Comment by jedireza** [comment]
https://github.com/jedireza/aqua/wiki/Users,-Roles-&-Groups

**Comment by rocky1138** [comment]
Sorry, I'm super thick when it comes to this stuff. I appreciate your help! What I'm referring to is "linking" in this sense: https://github.com/jedireza/aqua/blob/master/server/api/accounts.js#L280

What am I missing?
