### ISSUE TITLE
Can not run test (on Windows 10)

### ISSUE THREAD

**Issue by e8315402** [jedireza/aqua#259]
Thanks for this awesome project help me to save the time.

And as title, it's working well on Windows using _npm start_, but when I try to run the test using _npm test_, it just fails with the error message:
```
E:\Projects\aqua>npm test

> aqua@7.0.2 test E:\Projects\aqua
> lab -t 99 -S -T ./test/lab/transform ./test/lab/client-before.js ./test/client/ ./test/lab/client-after.js ./test/server/ ./test/lab/server-after.js ./test/misc/

Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received undefined at index 2.
E:\Projects\aqua\test\client\pages\admin\components\filter-form-fixture.jsx:26
            <div>
            ^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at ....
```

I also try it on my Mac, and it can run all tests(although there are some tests fail).

Does somebody meet the same situation? Could fix this problem? Thanks.

**Comment by jedireza** [comment]
> `SyntaxError: Unexpected token <`

Sounds like something isn't setup properly. Possibly related to babel and/or jsx not being parsed correctly.

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
