### ISSUE TITLE
sending welcome email failed: Error: Invalid login

### ISSUE THREAD

**Issue by MetaCoderHirschl** [jedireza/aqua#26]
Receive Invalid login although credentials are correct in `/config.js` (not shown here but correct in file):

```
nodemailer: {
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
        user: '**a@gmail.com',
        pass: '***'
    }
},
```

**Comment by jedireza** [comment]
I added the page [Issues using Gmail SMTP](https://github.com/jedireza/aqua/wiki/Issues-using-Gmail-SMTP) to the wiki. Could those potential causes be relevant?
