### ISSUE TITLE
Support multiple user sessions

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#260]
See: https://github.com/jedireza/frame/issues/180

**Comment by vmetayer** [comment]
Does the current version of aqua only allow one logged in user at a time?

**Comment by jedireza** [comment]
Haha. No. But it does limit each logged in user to one session.

**Comment by vmetayer** [comment]
Sorry for my lack of knowledge, but is there a session timeout atleast? Seems like a nice to have feature tho.

**Comment by jedireza** [comment]
Sure thing. By default, we're just using [`hapi-auth-cookie`](https://github.com/hapijs/hapi-auth-cookie) internally:

 - https://github.com/jedireza/aqua/blob/ea085be912494561149e1899d68cb468e5e0d144/server/auth.js#L15-L21

And you could swap out `hapi-auth-cookie` for whatever strategy works best for your project.

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
