### ISSUE TITLE
Hapi v17

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#268]
Hapi v17 is a full rewrite and will cause some big changes.

 - https://github.com/hapijs/hapi/issues/3658

~~We need `mongo-models` and `hapi-mongo-modles` to get updated and then we should be in good shape to begin the migration. Help on these modules would be much appreciated 🙏.~~

 - [X] https://github.com/jedireza/mongo-models/issues/24
 - [x] https://github.com/jedireza/hapi-mongo-models/issues/74

~~We also need Frame to get updated for Hapi 17 first since we'll copy most of the code changes.~~

 - [x] https://github.com/jedireza/frame/issues/186

**Comment by rnavok** [comment]
Hi there :)
Any estimation on the V17 rewrite release?
Thank you much in advance
R

**Comment by jedireza** [comment]
Nope. I work on it when I can.

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
