### ISSUE TITLE
Integrating Aqua with a non-Node.js website

### ISSUE THREAD

**Issue by ndilekli** [jedireza/aqua#269]
I have a classic website (site X) that is build using regular HTML and JS. I wonder if Aqua could be integrated with such a site. Going to the site X without authentication would redirect to the Aqua site. And after a successful login Aqua would redirect to the site X. If possible, how would it be done?

Thanks

**Comment by jedireza** [comment]
Aqua is a boilerplate application. It's meant to be used to start new projects. Integrating it into your existing site could be an over-complicated burden.

As every situation is different, it's hard to give general advice in this case.
