### ISSUE TITLE
Some wiki links are broken

### ISSUE THREAD

**Issue by jloriente** [jedireza/aqua#270]
https://github.com/jedireza/aqua/wiki

**Comment by jedireza** [comment]
Thanks for calling this out. Luckily the content is still there. I think the markup link rules have changed. The links on the right still work.

<img width="1025" alt="screen shot 2017-11-26 at 12 48 16 pm" src="https://user-images.githubusercontent.com/979929/33244203-4c758f22-d2a8-11e7-9179-6518c66a1640.png">

**Comment by jedireza** [comment]
I recently fixed these links manually.

**Comment by jloriente** [comment]
Ok thanks.
