### ISSUE TITLE
Mongo indexes `unique: 1` is in wrong place

### ISSUE THREAD

**Issue by symbianm** [jedireza/aqua#272]
Based on [Mongo documentation](https://docs.mongodb.com/manual/reference/command/createIndexes/index.html#example) `unique: true` should be outside of the `key` object.

https://github.com/jedireza/aqua/blob/ea085be912494561149e1899d68cb468e5e0d144/server/models/user.js#L203-L206

Proper structure example:
```
User.indexes = [ 
     { key: { username: 1 }, unique: true }, 
     { key: { email: 1 }, unique: true } 
 ]; 
```

**Comment by jedireza** [comment]
Yep. We need a PR just like https://github.com/jedireza/frame/pull/178

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
