### ISSUE TITLE
Bug when creating Admin-Groups "Admin"

### ISSUE THREAD

**Issue by jfvb** [jedireza/aqua#274]
Hi,

When i am creating users, i am creating Admin-Groups "Admin", and I am creating Admins with Admin-Groups "Admin" and i link with one user.
I am logout.
When i login with the new Admin account, i am the fix bug in the serveur ;

Debug: pre, error 
    {"msec":0.24384796619415283,"assign":"ensureAdminGroup","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Missing admin group membership to [root]."},"headers":{}}}}

Are You please issue for that problem ?
Thanks too much for you answers
Best Regards.

**Comment by jedireza** [comment]
> Missing admin group membership to [root].

Sounds like you're trying to access an endpoint that requires being part of the root admin group.
