### ISSUE TITLE
Password appears in address bar

### ISSUE THREAD

**Issue by xapple** [jedireza/aqua#277]
Hi !

I just installed `aqua` on a virtual server to check it out, and as I attempted to sign-in with some fake credentials, I noticed that the user name and password are placed in the URL. Am I missing something or is this an oversight ?

<img width="1320" alt="screen shot 2018-02-04 at 23 00 20" src="https://user-images.githubusercontent.com/649288/35782898-baa217b6-09ff-11e8-93ba-2dd3c95f2c8e.png">

**Comment by jedireza** [comment]
Thanks for creating an issue. I've only seen this when the react app hasn't mounted on the page yet. This can be avoided and we should fix it.

An easy fix would be to change the `form` tag's `method` attribute to `post`.

**Comment by jedireza** [comment]
I've decided to archive this project. Thank you for your interest and contributions.
https://github.com/jedireza/aqua#no-longer-maintained
