### ISSUE TITLE
Proposal: use ooth for the user management part

### ISSUE THREAD

**Issue by nmaro** [jedireza/aqua#278]
Hi there, I'm the developer of [ooth](https://github.com/nmaro/ooth), a modular user identity management system built on top of passport.js (which, famously, only handles the authentication part, but not the storage of user information part).

You have a nice starter here, but if people want to extend the login functionality with other strategies (e.g. facebook or google login) they are on their own. With ooth they could just plug in another strategy and move. What do you think?

**Comment by jedireza** [comment]
Thanks for sharing. For 3rd party authentication folks in the hapi eco-system can also reach for [`bell`](https://github.com/hapijs/bell).
