### ISSUE TITLE
System mailer connection errors 

### ISSUE THREAD

**Issue by StewartNoyce** [jedireza/aqua#28]
I'm excited to use Aqua for Hapi (dynamic route generation) and React (consistent client-server html).  And the setup module is a nice touch.  It was definitely a hassle to set up the database the first time with each new install.  Now the problem.  
I work with domains hosted on Network Solutions, Bluehost and Earthlink.  None of these worked properly as a secure system mailer with Aqua.  So, I ran a test.  
Using [foundeo](http://foundeo.com/products/iis-weak-ssl-ciphers/test.cfm) to test support for the secure protocol layer, I found that Earthlink doesn't support SSL or TLS, and Network Solutions and Bluehost both support TLSv1.  
For the test, nodemailer host and auth properties were set for each system mailer, port was set to 587, and secure was set to true.  In both cases, the sign in form hung with a user name / password that had been created.  The forgot password route generated:
    Error: 2686104896:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:787:

Looking more closely with openssl run from the command line, Network Solutions returns a number of errors including "num=20:unable to get local issuer certificate", "num=27:certificate not trusted", "num=21:unable to verify the first certificate", "No client certificate CA names sent" and finally "Verify return code: 21 (unable to verify the first certificate)."  Bluehost returns "num=20:unable to get local issuer certificate", "No client certificate CA names sent" and finally "Verify return code: 20 (unable to get local issuer certificate).  
So, I have a few questions:  
First, what's going on here?  What is the local issuer certificate in this context?  
Second, does secure email require a certificate on the smtp server side for each private domain?  
Third, what works out-of-the-box?  Is gmail with SSL (default configuration) the only option?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> First, what's going on here? What is the local issuer certificate in this context?
> Second, does secure email require a certificate on the smtp server side for each private domain?

These questions are better suited for the [Nodemailer](http://www.nodemailer.com/) team. We use Nodemailer for email transport and simply wire it up via a plugin here:
https://github.com/jedireza/aqua/blob/master/server/mailer.js, passing config options to it.

> Third, what works out-of-the-box? Is gmail with SSL (default configuration) the only option?

I have not worked with hosting on Network Solutions, Bluehost or Earthlink. I've have successfully used [AWS SES](http://aws.amazon.com/ses/) and Gmail.
