### ISSUE TITLE
Understanding Users Accounts and Groups

### ISSUE THREAD

**Issue by gazzer82** [jedireza/aqua#30]
Hi,

I have just come across this framework and it seems like a great jumping off place for a project i am playing with. However i am not quite understanding the logic behind the user management.

What i am looking to do is to create some ACL groups that users can belong to, only the admin can add/remove the user from that group, users can belong to multiple groups, and groups can have multiple users. I think i can do this using the Admin Groups and assigning the account to the user and the user to the admin group, but that seems like it has an additional necessary step? Would it not make more sense for all the user information to be in one object, Account and for that to be able to be allocated groups, that i can then query when requests hit the restAPI e.t.c?

I'm probably completely misunderstanding the setup here, so please do correct me if i am wrong!

Thanks

Gareth

**Comment by jedireza** [comment]
Thanks for opening an issue. :cake: 

> I have just come across this framework and it seems like a great jumping off place...

Not to banter about terminology, but it's a boilerplate not a framework. :stuck_out_tongue_winking_eye: 

> However i am not quite understanding the logic behind the user management.

Although these links are for [Drywall](https://github.com/jedireza/drywall/) and the code is different, the semantics are very similar.

 - https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups
 - https://github.com/jedireza/drywall/wiki/Admin-%26-Admin-Group-Permissions

I should port those pages over to the wiki here. Hopefully these help for the time being.

> I think i can do this using the Admin Groups and assigning the account to the user and the user to the admin group, but that seems like it has an additional necessary step?

Like I mention at the bottom of the the [_Users, Roles & Groups_](https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups) wiki page, it's may be good to extend the group functionality to accounts. Also keep in mind that we're working with a non-relational db and data is de-normalized.

- - - - -

Your milage may vary. Hopefully this project can inspire a solution that works best for you use case.

Let's keep this issue open as a reminder to port those wiki pages over.

:pray: thanks for getting involved.
