### ISSUE TITLE
Faster development process

### ISSUE THREAD

**Issue by moaiandin** [jedireza/aqua#33]
Just been developing a new application based on your project in the last few weeks and first to say, wonderful work. Although i've found a couple of issues which I think would be wonderful if we get fixed/changed, wanted to know your opinion: 

1. When developing, Every time a change is made and file is save the code triggers full cleaning and uglifying which takes a while and hence we have to wait for the updates to be visible on the front-end. Would be nice to separate the build for dev and production environment so when developing a lot of those steps are skipped.

2. For the front-end when making changes currently we need to refresh the page, May I suggest BrowserSync?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> When developing, Every time a change is made and file is save the code triggers full cleaning and uglifying which takes a while and hence we have to wait for the updates to be visible on the front-end. Would be nice to separate the build for dev and production environment so when developing a lot of those steps are skipped.

When I start the app with `$ npm start` it is running the default gulp task. The default task will start the server and watch for asset changes and only run tasks related to those changes. So when I make changes locally webpack only builds the relevant files.

Are you running the app differently?

> For the front-end when making changes currently we need to refresh the page, May I suggest BrowserSync?

I think this is a good change to leave out. This could make for a good wiki guide though. Would you like to help with that?
