### ISSUE TITLE
Create wiki pages for users/roles/groups

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#34]
Related: #30 

We should migrate the content from these pages:

 - https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups
 - https://github.com/jedireza/drywall/wiki/Admin-%26-Admin-Group-Permissions

**Comment by tegamckinney** [comment]
+1

**Comment by AdamQuadmon** [comment]
Didn't you already did it here?
[Frame/Users, Roles & Groups](https://github.com/jedireza/frame/wiki/Users,-Roles-&-Groups)
[Frame/Admin & Admin Group Permissions](https://github.com/jedireza/frame/wiki/Admin-%26-Admin-Group-Permissions)

**Comment by jedireza** [comment]
@AdamQuadmon yes, I wanted to migrate that content to the wiki in Aqua though.

**Comment by jedireza** [comment]
The wiki has been updated (https://github.com/jedireza/aqua/wiki).
