### ISSUE TITLE
Server start can fail due to plugins not loaded in the right order

### ISSUE THREAD

**Issue by FennNaten** [jedireza/aqua#36]
Hi,
I was looking at the aqua code, and I remarked that the registration of the auth schemes and strategy prior to routes is not enforced.
As plugins are declared in a Glue manifest, which takes them as an object and iterates over the keys to register them, load order isn't guaranteed. Therefore, server start can fail, if registration of strategies occurs before one of the schemes, or registration of one of the routes occurs before strategies. 
Preventing this requires marking strategies registration plugin dependant on schemes plugins, and route plugins using auth dependant on strategies plugin, via plugin attributes, to let hapi server resolve the registration order. Or maybe using prePlugins Glue option to manually register the auth part. 
This problem is refferred to in hapijs/glue#19

**Comment by zoe-1** [comment]
@jedireza and @FennNaten , 
@marsup provided the solution for the load order issue defined at: https://github.com/hapijs/glue/issues/19 
I contacted him on gitter to clarify what he meant by "use dependencies for that" in order to ensure load order.  He referenced using http://hapijs.com/api#serverdependencydependencies-after logic to ensure that a plugin's dependencies load before the plugin.

**Comment by jedireza** [comment]
Thanks for creating an issue. We could add a `dependencies` attribute to the plugins where needed to make it explicit.

Besides the auth plugin, we may want to do this for all plugins. As an example:

```js
exports.register.attributes = {
    name: 'login',
    dependencies: ['hapi-mongo-models']
};
```

https://github.com/jedireza/aqua/blob/master/server/api/login.js#L304-L306

**Comment by zoe-1** [comment]
Based on conversation with @marsup on gitter adding dependencies in attributes does not 
ensure the a plugin's dependencies load before the plugin. He says must use dependencies-after logic referenced above.

**Comment by zoe-1** [comment]
Today, @csrl made a post at clarifying things regarding making glue's load order deterministic. Plus, he also talks about the proper way of handling plugin dependencies in hapi with glue.
https://github.com/hapijs/glue/issues/19

**Comment by zoe-1** [comment]
@jedireza 
After researching this glue load dependencies issue for a while, I have concluded that 
@Marsup is right.  Using the below method to load dependencies before a plugin is registered
is not bullet proof.
```
exports.register.attributes = {
    name: 'login',
    dependencies: ['hapi-mongo-models']
};
``` 
It seems we must use the less elegant method to load plugins to bullet proof it:
See my comments at:
https://github.com/hapijs/university/pull/137
Your perspective would be appreciated.
Cheers!

**Comment by FennNaten** [comment]
Hi,
I investigated the issue in full (I think/hope) and you can find all the details here: [1a3494909e2]( https://github.com/FennNaten/hueniversity/commit/1a3494909e207166c6a12e60c8ca9a79f229ba73 )

a small TL;DR : using attributes is not enough, as they don't prevent all the code in plugin.register methods to be executed in whatever order. They only enforce on-start dependency check with error throwing if a dependency is missing. 
This let two ways for handling the issue:
- decorate each plugin making use of methods from another plugin in its register method with a server.dependency call. Considering that in aqua it's at least all of the plugins registering routes with auth, it may not be the most practical approach, even if it's the cleanest.
- use the prePlugins option of Glue. It takes a function which will be called before any plugin registration declared in the manifest, so you can move here a manual registration of critical plugins. It's not as best as the previous option for conveying intent, and you lose the ability to declare everything directly in manifest, but it's quick to do and it works.

Regards.

**Comment by jedireza** [comment]
Too bad Glue isn't handling this for us. I take it it's not something that belongs in Glue?

If this is something that should change in Aqua, I'd like to compare some solutions. I'm on holiday currently and have limited time. Is anyone interested in showing some example solutions?

**Comment by Marsup** [comment]
Why would glue solve a problem that doesn't exist ? Use hapi dependencies, it's made for that purpose.

**Comment by jedireza** [comment]
I chatted with @Marsup on Gitter and clarified my understanding. :wink:

If there two ways to handle the issue, I'd like to compare them. @zoe-1 or @FennNaten feel free to show some example solutions before we roll forward with a PR.

**Comment by FennNaten** [comment]
Hi, I don't have a lot of time this week, but I quickly put up examples of how the two methods would be used.
See there: [prePlugins example] ( https://github.com/FennNaten/aqua/tree/sample/setting-deps-on-preplugins ) and there: [server.dependency example] ( https://github.com/FennNaten/aqua/tree/sample/setting-deps-via-server-register )
Please note those aren't complete or fully tested, it's only a demo.

**Comment by jedireza** [comment]
@FennNaten thanks for creating these examples. I'm still on holiday and I'd like to spend some time on this when I'm back.

I did quickly compared the diffs and the `server.dependency` seems like a better approach since the `prePlugins` example removes a lot away from the manifest.
