### ISSUE TITLE
sorting not working on demo

### ISSUE THREAD

**Issue by jskye** [jedireza/aqua#40]
sorting of user accounts not working on demo? this on purpose?
was working on drywall demo.

**Comment by jedireza** [comment]
Thanks for creating an issue and reporting this bug. I checked the live demo and confirmed that the results are not sorting as expected. I'm remember this working. We'll need to investigate and find out what's changed.

**Comment by jedireza** [comment]
This must have been broken since we upgraded react-router a while back. We were not calling `transitionTo` correctly. You can see the diff here: https://github.com/jedireza/aqua/pull/46/files

Thanks again for reporting this.
