### ISSUE TITLE
Password reset link is invalid

### ISSUE THREAD

**Issue by alexbooker** [jedireza/aqua#41]
I am playin' around with the [demo](https://getaqua.herokuapp.com/) and noticed that the password reset email has an invalid link:

> We received a request to reset the password for your account. You'll need this key to do it.

> Key:
> undefined/login/reset/alexbooker@fastmail.im/88d8105a-6556-4ebc-92b9-6a3c1231231

> Love,

> The Plot Device

**Comment by jedireza** [comment]
Thanks for reporting this.

**Comment by jedireza** [comment]
This is fixed now. I was missing the `baseUrl` config option.

**Comment by alexbooker** [comment]
Nice one
