### ISSUE TITLE
deployment heroku

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#48]
any helpful steps?
1. setup dyno
2. add mongolab addon
3. deploy to heroku 
:-(

**Comment by rstormsf** [comment]
Ohhh I've just noticed `config.js` is being ignored...let me add it

**Comment by rstormsf** [comment]
checking heroku logs

```
2015-07-31T20:41:07.035275+00:00 app[web.1]: sh: 1: gulp: not found
```
i think that's why

**Comment by jedireza** [comment]
Thanks for opening an issue. I think the wiki page will help: https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku

**Comment by rstormsf** [comment]
Ohhh sorry about that. I didn't see this wiki page

**Comment by jedireza** [comment]
No worries at all. :stuck_out_tongue_winking_eye:

**Comment by rstormsf** [comment]
https://aqua-cb.herokuapp.com/ - I had to make `NODE_ENV=production`

**Comment by rstormsf** [comment]
another issue with wiki doc for deploying to heroku is that since we ignore `public` folder, our assets are not included.
Solution: move out to separate folder + add gulp task to copy/paste them into public(fonts+images)

**Comment by rstormsf** [comment]
I've also added to `package.json`

```
"engines": {
    "node": "0.12.x"
  }
```

**Comment by jedireza** [comment]
> https://aqua-cb.herokuapp.com/ - I had to make NODE_ENV=production
> and
> heroku run node setup.js
> I think it will be useful to add to wiki

Great suggestion. I added the section [Seeding your database](https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#seeding-your-database) to the wiki page.

> another issue with wiki doc for deploying to heroku is that since we ignore public folder, our assets are not included.

I liked the media change in your PR, just need to split the other change apart or remove it.

> I've also added to package.json
> "engines": {
>     "node": "0.12.x"
> }

Aqua should still work with node 0.10.x, 0.11.x and 0.12.x. We're testing all three on Travis.

**Comment by rstormsf** [comment]
I wanted to do 2 separate pull requests and for some reason, when I committed a second change, it automatically added to first pull request :-(

**Comment by rstormsf** [comment]
FYI - I'm looking for a new job right now, let me know if you know some good place to code.

**Comment by jedireza** [comment]
> I wanted to do 2 separate pull requests and for some reason, when I committed a second change, it automatically added to first pull request :-(

You can remove/amend your commits in #51 

> FYI - I'm looking for a new job right now, let me know if you know some good place to code.

 - https://news.ycombinator.com/item?id=9996333
 - http://careers.stackoverflow.com/jobs/tag/nodejs
 - https://github.com/nodeschool/jobs/issues
