### ISSUE TITLE
Why such comparison to array

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#50]
https://github.com/jedireza/aqua/blob/master/server/auth.js#L78

I was just curious, there are so many other ways to see if it's an array, why did you decide to go this way?
```
            if (Object.prototype.toString.call(groups) !== '[object Array]') {
                groups = [groups];
            }
```

**Comment by jedireza** [comment]
Good question. I vaguely remember looking this up back then. I just searched [javascript check for array](https://www.google.com/search?q=javascript+check+for+array) and found this [StackOverflow answer](http://stackoverflow.com/a/4775737) regarding this.
