### ISSUE TITLE
forgot password link doesn't work if I'm logged in

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#52]
I assume I should be navigated to the forgot password page even though I'm logged in.
It just redirects to account page

**Comment by rstormsf** [comment]
I'm trying to understand the architecture here, but I can't even see how `/login/forgot` gets rendered. there is no route for 'GET' request, only for posts in api.
because I assume api redirects it to `/account` if user is logged in

**Comment by rstormsf** [comment]
figured it out
https://github.com/jedireza/aqua/blob/master/server/web/login/index.js#L26
that's what makes it to redirect

**Comment by rstormsf** [comment]
Wow! Now I'm confused, 
how does forgot password view render? I've just setup a breakpoint in WebStorm and I see it gets there, and calls 
```
var response = reply.view('login/index'); (which has nothing to do with forgot password page)
```
then it somehow goes to client side to Router.jsx for login component, reads current path and fires handler for Forgot component. 

Need to spend more time to learn how it works

**Comment by rstormsf** [comment]
added a commit to my prev pull request.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Wow! Now I'm confused, how does forgot password view render? I've just setup a breakpoint in WebStorm and I see it gets there, and calls 

Aqua is like a handful of single page apps. You can see how we break them out here:
https://github.com/jedireza/aqua/blob/master/gulp/webpack.js#L16-L20

The SPAs (single page apps) that have multiple routes, have a client-side router:

 - https://github.com/jedireza/aqua/blob/master/client/pages/account/Routes.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/admin/Routes.jsx
 - https://github.com/jedireza/aqua/blob/master/client/pages/login/Routes.jsx

So on the server, we only need to render the main payload and the client takes over once we render in the browser.

I hope this helps.

- - - - - -

I need to annotate the app structure and design as a wiki page. I've opened #54 to serve as a reminder to do that.
