### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by ADumaine** [jedireza/aqua#55]
For anyone trying to install under windows this may help to get aqua running:

When running install if you have bcrypt or other issues withing compiling try using the "--msvs-version=2013" flag: npm install --msvs-version=2013  (if you have that installed or try a later version if that is what you have).  I had so slog though all the bcrypt install solutions find something that worked.

"npm run setup"  threw an error on ./setup.js.  I had to remove the "./" on line 7 ("setup" : "./setup.js") of package.json so windows would not complain.

"npm run setup" also just kept opening setup.js instead of prompting. I got it to run setup just using: node setup.js

I have it running, but have not tried the testing.  I assume it may complain about the test paths also using "./"  instead of ".\"  in package.json. These may need to be changed too.

**Comment by jedireza** [comment]
Thanks for opening an issue and sharing these details.

Do you think we should add some of these details to the [bcrypt-Installation-Trouble](https://github.com/jedireza/aqua/wiki/bcrypt-Installation-Trouble) wiki page?

**Comment by ADumaine** [comment]
Yes adding some of the items to the wiki may be helpful.  I started with
drywall and went through the links along with other items I found.  It took
a few hours to get bcrypt installed.  I actually had to use another
work-around (cheat actually). see below.  When I installed aqua i was able
to use the --msvs-version switch.  Would you like me to edit it?

I don't think the path issues in package.json and the npm run setup issues
should go on the bcrypt page though.  I don't know why npm does not handle
the ./ in the path to setup.js.  Just removing the ./ from the package.json
should suffice.

I also don't understand why running 'npm run setup' just kept opening
setup.js in my editor. A note about that in the install instructions to try
running 'node setup.js' directly should suffice.


Alternate bcrypt install work-around (ran into this installing bcrypt for
drywall):
 I had some VS 2010 redistributables installed, but I also had VS 2013
Express and VS 2015 community. I kept getting an error message looking for
MSBuild in a folder call V110 in 'C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0'.  I only had V120 and V140.  Out of
frustration I renamed V120 to V110 to get the install to work and renamed
it after.  Later found the --msvs-version=2013 parameter.

Allan Dumaine
480 342-9045

**Comment by jedireza** [comment]
> Yes adding some of the items to the wiki may be helpful. I started with drywall and went through the links along with other items I found. It took a few hours to get bcrypt installed. I actually had to use another work-around (cheat actually). see below. When I installed aqua i was able to use the --msvs-version switch. Would you like me to edit it?

Sure. Let me know when it's been updated.

> I don't think the path issues in package.json and the npm run setup issues should go on the bcrypt page though. I don't know why npm does not handle the ./ in the path to setup.js. Just removing the ./ from the package.json should suffice.

Bummer. I took the `./` out of the setup script and it fails on a mac. Keep in mind that the `setup.js` file is executable (ex: `chmod +x`).
