### ISSUE TITLE
Posible to use mongolab as remote mongodb? like drywall?

### ISSUE THREAD

**Issue by JimVercoelen** [jedireza/aqua#56]
Hi,

I was wondering if it is possible to use a remote mongodb server like in your drywall repository?
By using the same set-up?

If not, i supose I need to create a new db inside local mongodb and then following the set-up?

Regards

ps. just started learning node and do like drywall!

**Comment by jedireza** [comment]
Sure thing, you'll need to set the mongodb configuration url to the remote database (same concept as the Drywall config).

https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/config.example#L35-L55

**Comment by jedireza** [comment]
You may also want to read this part of the wiki, as it may be relevant:
https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#seeding-your-database

**Comment by JimVercoelen** [comment]
Hey jederiza,

Thanks for your response which also was very fast!
