### ISSUE TITLE
Expected behavior of unlink a user

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#61]
Currently it throws an error:

```
 {"msec":4.509436011314392,"error":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","data":{"name":"MongoError","message":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","errmsg":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","code":9,"ok":0,"isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
Debug: internal, error
```
what does unlink a user should do?

**Comment by jedireza** [comment]
Here are some code points related to Account, there is similar stuff for Admins:

 - https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/client/pages/admin/actions/Account.js#L77-L99
 - https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/server/models/account.js#L21-L24
 - https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/server/api/accounts.js#L361-L449

Unlinking a User from an Account or an Admin record removes the relationship essentially. The error you're showing is that `$unset` is empty. But where we do this [1][2] it isn't empty. Can you double check or create steps to reproduce the error?

[1] https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/server/api/accounts.js#L421-L423
[2] https://github.com/jedireza/aqua/blob/75932ff7d32eb9389c3f67093965b97f93955d96/server/api/admins.js#L441-L443

**Comment by alphastorm** [comment]
I'm experiencing the exact same behaviour, here are the steps to reproduce:

1. git clone https://github.com/jedireza/aqua.git webapp && cd webapp
2. npm install
3. npm setup (fill out everything correctly)
4. npm start

This error happens immediately after starting the server:

```javascript
Debug: handler, error
    {"msec":2.0037779957056046,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}}
```

5. Reset the admin account's password and follow the reset URL (e.g. http://127.0.0.1:8000/login/reset/test@example.com/465522ac-e3d9-45be-b53e-236ba6ce5082)
6. When you submit the reset password request, you get this error in console:

```javascript
Debug: handler, error
    {"msec":147.42717298865318,"error":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","data":{"name":"MongoError","message":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","errmsg":"exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}","code":9,"ok":0,"isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
Debug: internal, error
    MongoError: exception: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}
    at Function.MongoError.create (/home/users/sunil/Development/shellsaver/webapp/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/users/sunil/Development/shellsaver/webapp/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:754:66
    at Callbacks.emit (/home/users/sunil/Development/shellsaver/webapp/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/users/sunil/Development/shellsaver/webapp/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/home/users/sunil/Development/shellsaver/webapp/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

Any help would be appreciated.

**Comment by jedireza** [comment]
@alphastorm thanks for adding steps to reproduce. I will check this out when I get some time. If anyone else want's to debug and/or create a PR ... please do.

**Comment by alphastorm** [comment]
@jedireza thanks for the quick response!  I would have done more digging myself but the stack trace isn't really helpful so wanted to reach out first :)
