### ISSUE TITLE
adding entry for webpack requires to re run an app

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#62]
enhancement to consider

**Comment by jedireza** [comment]
> adding entry for webpack requires to re run an app

Yup that's right. Do you know how to get around that?

**Comment by rstormsf** [comment]
hmmmm....
https://github.com/webpack/webpack/issues/118
https://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Advanced Usage

**Comment by jedireza** [comment]
Closing for now. Feel free to send a PR for review.
