### ISSUE TITLE
MongoLab 3 Auth Issue!

### ISSUE THREAD

**Issue by DHidee66** [jedireza/aqua#69]
Hi,

I am having an authentication error with MongoLab. Is it because they started using mongo v3?
![screen shot 2015-10-27 at 6 39 04 pm](https://cloud.githubusercontent.com/assets/6751025/10766954/36c05606-7cda-11e5-94cf-53331a6e23a5.png)

Thank You!

**Comment by jedireza** [comment]
Thanks for opening an issue.

I don't think this is related to MongoLab or MongoDB in general. If you look at the stack there it's pointing to `/app/node_modules/hapi/lib/handler.js`.

This sounds like you updated your version of `hapi`. In newer versions of `hapi` they removed the file/directory handler stuff from core and moved it to a module called [`inert`](https://github.com/hapijs/inert). Just add that to your project and it should fix this specific issue.

**Comment by DHidee66** [comment]
Thank you for your help :)

**Comment by jedireza** [comment]
:+1: :tada:
