### ISSUE TITLE
Hapi package is insecure

### ISSUE THREAD

**Issue by ThemeSurgeon** [jedireza/aqua#72]
Hapi package is reported as having an insecure CORS vulnerability, and should be updated to the 11.x.x patched version. Quite a few other packages, including react need to be updates I believe. Thanks very much for a great react starter project.

**Comment by jedireza** [comment]
Thanks for creating an issue. Yes we do need to update dependencies. I've been waiting for react-router to hit v1 before starting. It looks like that's happend so... we can start working on this.

**Comment by ThemeSurgeon** [comment]
Thank you. I'm thinking of using it for a class I am teaching in
Minneapolis. I think it provides a great foundation for student projects.
Yes, looks like them main roadblock is updates for react 0.14.3, but not
completely sure about that.

Best to you and yours,

John

John Teague
Founder
Theme Surgeons LLC
john@themesurgeons.com
https://themesurgeons.com

On Twitter <https://twitter.com/themeSurgeon> | Google+
<https://plus.google.com/+ThemesurgeonsWordPress/>
