### ISSUE TITLE
adding new data to this.state in GET_ACCOUNT_SETTINGS_RESPONSE

### ISSUE THREAD

**Issue by bennyticklez** [jedireza/aqua#76]
Not so much of an issue, more of a question!

I have a new text field in AccountsForm.jsx called "job". It has correctly added to the db as seen below:

    { _id: ObjectId("569a9fdf9b4fbb060a3f956a"), name: { first: "Dylan", middle: "James", last: "Thomas" }, timeCreated: ISODate("2016-01-16T19:54:07.334Z"), user: { id: "569a9fdf9b4fbb060a3f9569", name: "daylightdylan" }, job: "Web Dev" }

During onDispatcherAction > GET_ACCOUNT_SETTINGS_RESPONSE in account/stores/Account.js I can see that it is setting the this.state values using the values from action.data., which contains "name" and "timeCreated" however my new "job" variable does not exist. Where do I define/add my new variable to action.data so that it is available? I am new to this and I am completely lost! 

    this.handleResponseErrors(action.data);
    this.state.hydrated = true;
    this.state.name = action.data.name; ////exists
    this.state.job = action.data.job; ////does not exist
    this.state.timeCreated = action.data.timeCreated;  ////exists
    this.emitChange();

Thanks in advance

**Comment by jedireza** [comment]
If you're referring to:

 - `/client/pages/account/components/settings/AccountForm.jsx`

It gets data from the server endpoint `/api/accounts/my`. You'll notice we define the fields to return here here:

 - https://github.com/jedireza/aqua/blob/master/server/api/accounts.js#L96

You should be able to modify those fields and see your new `job` field on the client.
