### ISSUE TITLE
Upgrade glue to latest version

### ISSUE THREAD

**Issue by manubamba** [jedireza/aqua#77]
Configuration has considerably changed in the new version.

**Comment by jedireza** [comment]
Thanks for creating an issue. And yes, you're right Glue has changed a lot in the newest version. [Frame](https://github.com/jedireza/frame/) (just the API) has already been updated for this.

There is also a branch [`aqua/tree/update-deps`](https://github.com/jedireza/aqua/tree/update-deps) where I've started to update all the dependencies (including Glue). The remaining work there is to update the tests. One main issue with tests right now is incorrect test coverage being reported `lab-babel`. Contributions to this work is much appreciated :pray:.
