### ISSUE TITLE
Use dropdown menu

### ISSUE THREAD

**Issue by choy315** [jedireza/aqua#81]
How can i make a dropdown menu?
I found the style code in your code repository but i cannot guess how can i use it.

**Comment by jedireza** [comment]
Thanks for creating an issue. The dropdowns in our system are done with the `SelectControl` component:

https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/client/components/form/SelectControl.jsx
