### ISSUE TITLE
Difference between server/web/ and client/pages/ and public/pages/

### ISSUE THREAD

**Issue by gracedigital** [jedireza/aqua#83]
Sorry this is a newbie question... 
I'm guessing the webpack process creates the files in the public/pages folder - what is the difference between the files in the server/web folder and the client/pages folder?

Could anyone provide some guidance on how the routing process for a request like login works?

**Comment by hydrotik** [comment]
server/web is the location for your Hapi routing plugins and server side React views. . When you hit a route that is defined in your manifest as a view via Hapi/Node, it would point to a section/corresponding page in this folder. The React components within the server folder are processed/rendered prior to the page loading within the browser and transmitted to the browser as HTML. Anything dynamic in the page would be handled before this output is sent to the browser.

Within client/pages you have the client side code and components which are loaded into an existing  container within the page at the time the user. In the case of Hapi and React, index.jsx is where the React components are "bootstrapped" to the html container and the logic is initialized and run at that time. In this case it is up to the browser to process the javascript/logic and then render the results.

I would say a number of decisions determine which direction you would want to go in such as page optimization and the nature of the data and experience requirements. In some cases you can use the same components for both server side and client side which is considered isomorphic or universal javascript.

I'm sure there is a more eloquent way to describe this which I might not be conveying, so I would suggest taking a look at a couple of the articles below. Understanding the trade offs might help clarify the differences between the two.

https://medium.com/google-developers/tradeoffs-in-server-side-and-client-side-rendering-14dad8d4ff8b#.814i4uh8m
http://openmymind.net/2012/5/30/Client-Side-vs-Server-Side-Rendering/

**Comment by jedireza** [comment]
@gracedigital thanks for opening an issue and @hydrotik thanks for jumping in. :pray: 

@gracedigital, what follow up questions do you have?
