### ISSUE TITLE
Integrate Frame?

### ISSUE THREAD

**Issue by hydrotik** [jedireza/aqua#84]
With the more recent work being done within Frame, would be great to see Aqua as an example of how to implement that project here?

**Comment by jedireza** [comment]
Aqua started as a copy of Frame and added the front-end and changed to cookie/session authentication. I have a PR #79 open that updates lots of things, including some updates that Frame has already. Does that answer your question? If not, could you be more specific?

**Comment by hydrotik** [comment]
Yes this does help quite a bit! Sorry I missed this and thanks for getting back so quickly.
