### ISSUE TITLE
demo is throwing Uncaught TypeError: this.transitionTo is not a function

### ISSUE THREAD

**Issue by thomasmodeneis** [jedireza/aqua#87]
Hi,

I'm executing the demo to test and is not working, with the error:
`Uncaught TypeError: this.transitionTo is not a function`

Basically none of the buttons sort and search is working, error seems to be
        `this.transitionTo('admins', {}, this.refs.filters.state);`

Any ideas ?

Thanks

**Comment by jedireza** [comment]
Thanks for creating an issue. This sounds like you have a newer version of [`react-router`](https://github.com/reactjs/react-router).

I touch on this a bit in #79
