### ISSUE TITLE
Test commands is failing on clean master

### ISSUE THREAD

**Issue by pankajpatel** [jedireza/aqua#88]
Hello,

I forked the aqua repo for some experiments (and hopefully PR) but the tests are failing.

``` 
{ aqua: '3.3.4',
  npm: '3.8.3',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' } 
```

Is it something because of updated dependencies?

**Comment by jedireza** [comment]
It sure is. See #79

**Comment by pankajpatel** [comment]
shall I wait for the #79 to close?

**Comment by jedireza** [comment]
That's where the work is happening. Help is welcomed on that branch. I've been time poor as of late.

**Comment by pankajpatel** [comment]
Let me try on _update-deps_ branch, I hope I can help in there.
