### ISSUE TITLE
How is lout used in this package?

### ISSUE THREAD

**Issue by ADumaine** [jedireza/aqua#91]
lout is in the dependencies but I cannot figure out how it is implemented.

**Comment by jedireza** [comment]
Thanks for opening an issue. From the `lout` docs:

> `endpoint` - the path where the route will be registered. Default is `/docs`.

And you can see that with the live demo here:

 - https://getaqua.herokuapp.com/docs

**Comment by ADumaine** [comment]
Thanks.
What is confusing is that there is no mention of the lout /docs path anywhere in this aqua repository. And I could not find a link for it on the demo site. It would be very helpful to have it at least mentioned in the readme or commented in the code somewhere.

**Comment by jedireza** [comment]
Good point. Would you be willing to start a PR with an update to the README?

**Comment by ADumaine** [comment]
PR created.
