### ISSUE TITLE
Is there a list of public sites that use or started with aqua?

### ISSUE THREAD

**Issue by ADumaine** [jedireza/aqua#92]
Building an app with aqua really helped me understand react and flux. It would be helpful to see what others have done with it and how many sites exist.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Building an app with aqua really helped me understand react and flux.

That's nice to hear!

> It would be helpful to see what others have done with it and how many sites exist.

You can start with people who have [forked](https://github.com/jedireza/aqua/network) to see if anything interesting is there. I've never polled people so I'm not sure what's in the wild.
