### ISSUE TITLE
Babel causing inaccurate code coverage reports

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#95]
There's a bug in `babel` where it's not wrapping some non user generated code with auxiliary comments causing `lab` to report missing coverage.

A bug has been filed and can be followed here: ~~https://github.com/babel/babel/issues/4450~~ https://github.com/babel/babel/issues/2055

**Comment by forgetaboutme** [comment]
Is it also possible that its shows the wrong coverage %? I added new routes and when I run `npm test` it always show 100% code coverage.

**Comment by jedireza** [comment]
@forgetaboutme Unless the new route files are `require`d somewhere in the tree, they won't show up as needing coverage. Create test matching test files with no tests and you'll see the lack of coverage.

**Comment by jedireza** [comment]
Recently I noticed some strange code coverage results:

```
Coverage: 100.70% (-102/14494)
```

This needs to be investigated further.
