### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by jedireza** [jedireza/aqua#96]
The landing page (http://jedireza.github.io/aqua/) needs to get updated for the latest version. I'm thinking about replacing the videos with screenshots.

**Comment by FernandoBoza** [comment]
4 images replaces the videos?

**Comment by jedireza** [comment]
No, not only 4. More like what I have on Drywall (http://jedireza.github.io/drywall/).

I'm actually working on this right now. I have this old casperjs script (https://github.com/jedireza/drywall-screen-shots) that will take the screenshots for me.

I'm updating the code now to take the screenshots for Aqua. I'll drop a link in this thread to the new screen shot script when I'm done.

**Comment by jedireza** [comment]
The screenshots are generated.

https://github.com/jedireza/aqua-screenshots
